// Code generated by bpf2go; DO NOT EDIT.
//go:build linux && arm64

package profiler

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type CpuProfilerCpuProfilerConfig struct {
	_             structs.HostLayout
	TargetPid     uint32
	SampleRateHz  uint32
	CaptureKernel uint8
	CaptureUser   uint8
	FilterActive  uint8
	Pad           [1]uint8
}

type CpuProfilerStackCount struct {
	_           structs.HostLayout
	Count       uint64
	FirstSeenNs uint64
	LastSeenNs  uint64
}

type CpuProfilerStackKey struct {
	_             structs.HostLayout
	Pid           uint32
	Tgid          uint32
	UserStackId   int32
	KernelStackId int32
	Comm          [16]int8
}

// LoadCpuProfiler returns the embedded CollectionSpec for CpuProfiler.
func LoadCpuProfiler() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CpuProfilerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load CpuProfiler: %w", err)
	}

	return spec, err
}

// LoadCpuProfilerObjects loads CpuProfiler and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*CpuProfilerObjects
//	*CpuProfilerPrograms
//	*CpuProfilerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadCpuProfilerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadCpuProfiler()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// CpuProfilerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CpuProfilerSpecs struct {
	CpuProfilerProgramSpecs
	CpuProfilerMapSpecs
	CpuProfilerVariableSpecs
}

// CpuProfilerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CpuProfilerProgramSpecs struct {
	ProfileCpu *ebpf.ProgramSpec `ebpf:"profile_cpu"`
}

// CpuProfilerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CpuProfilerMapSpecs struct {
	CpuProfileEvents *ebpf.MapSpec `ebpf:"cpu_profile_events"`
	CpuProfilerCfg   *ebpf.MapSpec `ebpf:"cpu_profiler_cfg"`
	CpuStackCounts   *ebpf.MapSpec `ebpf:"cpu_stack_counts"`
	CpuStacks        *ebpf.MapSpec `ebpf:"cpu_stacks"`
	CpuTargetPids    *ebpf.MapSpec `ebpf:"cpu_target_pids"`
	DebugEvents      *ebpf.MapSpec `ebpf:"debug_events"`
	MsgBufferMem     *ebpf.MapSpec `ebpf:"msg_buffer_mem"`
	PidCache         *ebpf.MapSpec `ebpf:"pid_cache"`
	ValidPids        *ebpf.MapSpec `ebpf:"valid_pids"`
}

// CpuProfilerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type CpuProfilerVariableSpecs struct {
	FilterPids              *ebpf.VariableSpec `ebpf:"filter_pids"`
	G_bpfDebug              *ebpf.VariableSpec `ebpf:"g_bpf_debug"`
	G_bpfHeaderPropagation  *ebpf.VariableSpec `ebpf:"g_bpf_header_propagation"`
	G_bpfTraceparentEnabled *ebpf.VariableSpec `ebpf:"g_bpf_traceparent_enabled"`
	Ip4ip6Prefix            *ebpf.VariableSpec `ebpf:"ip4ip6_prefix"`
	Unused                  *ebpf.VariableSpec `ebpf:"unused"`
	UnusedHttp2             *ebpf.VariableSpec `ebpf:"unused_http2"`
}

// CpuProfilerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadCpuProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type CpuProfilerObjects struct {
	CpuProfilerPrograms
	CpuProfilerMaps
	CpuProfilerVariables
}

func (o *CpuProfilerObjects) Close() error {
	return _CpuProfilerClose(
		&o.CpuProfilerPrograms,
		&o.CpuProfilerMaps,
	)
}

// CpuProfilerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadCpuProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type CpuProfilerMaps struct {
	CpuProfileEvents *ebpf.Map `ebpf:"cpu_profile_events"`
	CpuProfilerCfg   *ebpf.Map `ebpf:"cpu_profiler_cfg"`
	CpuStackCounts   *ebpf.Map `ebpf:"cpu_stack_counts"`
	CpuStacks        *ebpf.Map `ebpf:"cpu_stacks"`
	CpuTargetPids    *ebpf.Map `ebpf:"cpu_target_pids"`
	DebugEvents      *ebpf.Map `ebpf:"debug_events"`
	MsgBufferMem     *ebpf.Map `ebpf:"msg_buffer_mem"`
	PidCache         *ebpf.Map `ebpf:"pid_cache"`
	ValidPids        *ebpf.Map `ebpf:"valid_pids"`
}

func (m *CpuProfilerMaps) Close() error {
	return _CpuProfilerClose(
		m.CpuProfileEvents,
		m.CpuProfilerCfg,
		m.CpuStackCounts,
		m.CpuStacks,
		m.CpuTargetPids,
		m.DebugEvents,
		m.MsgBufferMem,
		m.PidCache,
		m.ValidPids,
	)
}

// CpuProfilerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadCpuProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type CpuProfilerVariables struct {
	FilterPids              *ebpf.Variable `ebpf:"filter_pids"`
	G_bpfDebug              *ebpf.Variable `ebpf:"g_bpf_debug"`
	G_bpfHeaderPropagation  *ebpf.Variable `ebpf:"g_bpf_header_propagation"`
	G_bpfTraceparentEnabled *ebpf.Variable `ebpf:"g_bpf_traceparent_enabled"`
	Ip4ip6Prefix            *ebpf.Variable `ebpf:"ip4ip6_prefix"`
	Unused                  *ebpf.Variable `ebpf:"unused"`
	UnusedHttp2             *ebpf.Variable `ebpf:"unused_http2"`
}

// CpuProfilerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadCpuProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type CpuProfilerPrograms struct {
	ProfileCpu *ebpf.Program `ebpf:"profile_cpu"`
}

func (p *CpuProfilerPrograms) Close() error {
	return _CpuProfilerClose(
		p.ProfileCpu,
	)
}

func _CpuProfilerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cpuprofiler_arm64_bpfel.o
var _CpuProfilerBytes []byte
