// Code generated by bpf2go; DO NOT EDIT.
//go:build linux && (386 || amd64)

package profiler

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type MutexProfilerLockState struct {
	_              structs.HostLayout
	AcquireStartNs uint64
	AcquiredNs     uint64
	OwnerTid       uint32
	WaiterCount    uint32
	OwnerStackId   int32
	Pad            int32
}

type MutexProfilerMutexConfig struct {
	_                     structs.HostLayout
	TargetPid             uint32
	_                     [4]byte
	ContentionThresholdNs uint64
	HoldThresholdNs       uint64
	FilterActive          uint8
	Pad                   [3]uint8
	_                     [4]byte
}

type MutexProfilerMutexKey struct {
	_        structs.HostLayout
	LockAddr uint64
	StackId  int32
	Pad      uint32
}

type MutexProfilerMutexStats struct {
	_                structs.HostLayout
	TotalWaitNs      uint64
	TotalHoldNs      uint64
	ContentionCount  uint64
	AcquisitionCount uint64
	MaxWaitNs        uint64
	MaxHoldNs        uint64
	MinWaitNs        uint64
	MinHoldNs        uint64
}

type MutexProfilerPendingLock struct {
	_        structs.HostLayout
	LockAddr uint64
	StartNs  uint64
	StackId  int32
	Pad      int32
}

// LoadMutexProfiler returns the embedded CollectionSpec for MutexProfiler.
func LoadMutexProfiler() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MutexProfilerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load MutexProfiler: %w", err)
	}

	return spec, err
}

// LoadMutexProfilerObjects loads MutexProfiler and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*MutexProfilerObjects
//	*MutexProfilerPrograms
//	*MutexProfilerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadMutexProfilerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadMutexProfiler()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// MutexProfilerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MutexProfilerSpecs struct {
	MutexProfilerProgramSpecs
	MutexProfilerMapSpecs
	MutexProfilerVariableSpecs
}

// MutexProfilerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MutexProfilerProgramSpecs struct {
	TraceMutexLockEnter   *ebpf.ProgramSpec `ebpf:"trace_mutex_lock_enter"`
	TraceMutexLockExit    *ebpf.ProgramSpec `ebpf:"trace_mutex_lock_exit"`
	TraceMutexTrylockExit *ebpf.ProgramSpec `ebpf:"trace_mutex_trylock_exit"`
	TraceMutexUnlock      *ebpf.ProgramSpec `ebpf:"trace_mutex_unlock"`
}

// MutexProfilerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MutexProfilerMapSpecs struct {
	DebugEvents     *ebpf.MapSpec `ebpf:"debug_events"`
	LockStates      *ebpf.MapSpec `ebpf:"lock_states"`
	MsgBufferMem    *ebpf.MapSpec `ebpf:"msg_buffer_mem"`
	MutexCfg        *ebpf.MapSpec `ebpf:"mutex_cfg"`
	MutexEvents     *ebpf.MapSpec `ebpf:"mutex_events"`
	MutexStacks     *ebpf.MapSpec `ebpf:"mutex_stacks"`
	MutexStatsMap   *ebpf.MapSpec `ebpf:"mutex_stats_map"`
	MutexTargetPids *ebpf.MapSpec `ebpf:"mutex_target_pids"`
	PendingLocks    *ebpf.MapSpec `ebpf:"pending_locks"`
	PidCache        *ebpf.MapSpec `ebpf:"pid_cache"`
	ValidPids       *ebpf.MapSpec `ebpf:"valid_pids"`
}

// MutexProfilerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type MutexProfilerVariableSpecs struct {
	FilterPids              *ebpf.VariableSpec `ebpf:"filter_pids"`
	G_bpfDebug              *ebpf.VariableSpec `ebpf:"g_bpf_debug"`
	G_bpfHeaderPropagation  *ebpf.VariableSpec `ebpf:"g_bpf_header_propagation"`
	G_bpfTraceparentEnabled *ebpf.VariableSpec `ebpf:"g_bpf_traceparent_enabled"`
	Ip4ip6Prefix            *ebpf.VariableSpec `ebpf:"ip4ip6_prefix"`
	Unused                  *ebpf.VariableSpec `ebpf:"unused"`
	UnusedHttp2             *ebpf.VariableSpec `ebpf:"unused_http2"`
}

// MutexProfilerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadMutexProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type MutexProfilerObjects struct {
	MutexProfilerPrograms
	MutexProfilerMaps
	MutexProfilerVariables
}

func (o *MutexProfilerObjects) Close() error {
	return _MutexProfilerClose(
		&o.MutexProfilerPrograms,
		&o.MutexProfilerMaps,
	)
}

// MutexProfilerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadMutexProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type MutexProfilerMaps struct {
	DebugEvents     *ebpf.Map `ebpf:"debug_events"`
	LockStates      *ebpf.Map `ebpf:"lock_states"`
	MsgBufferMem    *ebpf.Map `ebpf:"msg_buffer_mem"`
	MutexCfg        *ebpf.Map `ebpf:"mutex_cfg"`
	MutexEvents     *ebpf.Map `ebpf:"mutex_events"`
	MutexStacks     *ebpf.Map `ebpf:"mutex_stacks"`
	MutexStatsMap   *ebpf.Map `ebpf:"mutex_stats_map"`
	MutexTargetPids *ebpf.Map `ebpf:"mutex_target_pids"`
	PendingLocks    *ebpf.Map `ebpf:"pending_locks"`
	PidCache        *ebpf.Map `ebpf:"pid_cache"`
	ValidPids       *ebpf.Map `ebpf:"valid_pids"`
}

func (m *MutexProfilerMaps) Close() error {
	return _MutexProfilerClose(
		m.DebugEvents,
		m.LockStates,
		m.MsgBufferMem,
		m.MutexCfg,
		m.MutexEvents,
		m.MutexStacks,
		m.MutexStatsMap,
		m.MutexTargetPids,
		m.PendingLocks,
		m.PidCache,
		m.ValidPids,
	)
}

// MutexProfilerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadMutexProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type MutexProfilerVariables struct {
	FilterPids              *ebpf.Variable `ebpf:"filter_pids"`
	G_bpfDebug              *ebpf.Variable `ebpf:"g_bpf_debug"`
	G_bpfHeaderPropagation  *ebpf.Variable `ebpf:"g_bpf_header_propagation"`
	G_bpfTraceparentEnabled *ebpf.Variable `ebpf:"g_bpf_traceparent_enabled"`
	Ip4ip6Prefix            *ebpf.Variable `ebpf:"ip4ip6_prefix"`
	Unused                  *ebpf.Variable `ebpf:"unused"`
	UnusedHttp2             *ebpf.Variable `ebpf:"unused_http2"`
}

// MutexProfilerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadMutexProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type MutexProfilerPrograms struct {
	TraceMutexLockEnter   *ebpf.Program `ebpf:"trace_mutex_lock_enter"`
	TraceMutexLockExit    *ebpf.Program `ebpf:"trace_mutex_lock_exit"`
	TraceMutexTrylockExit *ebpf.Program `ebpf:"trace_mutex_trylock_exit"`
	TraceMutexUnlock      *ebpf.Program `ebpf:"trace_mutex_unlock"`
}

func (p *MutexProfilerPrograms) Close() error {
	return _MutexProfilerClose(
		p.TraceMutexLockEnter,
		p.TraceMutexLockExit,
		p.TraceMutexTrylockExit,
		p.TraceMutexUnlock,
	)
}

func _MutexProfilerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed mutexprofiler_x86_bpfel.o
var _MutexProfilerBytes []byte
