// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64

package profiler

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type OffcpuProfilerOffcpuConfig struct {
	_             structs.HostLayout
	TargetPid     uint32
	_             [4]byte
	MinBlockNs    uint64
	CaptureKernel uint8
	CaptureUser   uint8
	FilterActive  uint8
	Pad           [5]uint8
}

type OffcpuProfilerOffcpuKey struct {
	_             structs.HostLayout
	Pid           uint32
	Tgid          uint32
	UserStackId   int32
	KernelStackId int32
	Comm          [16]int8
	BlockReason   uint8
	Pad           [3]uint8
}

type OffcpuProfilerOffcpuStart struct {
	_             structs.HostLayout
	StartNs       uint64
	UserStackId   int32
	KernelStackId int32
	Reason        uint8
	Pad           [7]uint8
}

type OffcpuProfilerOffcpuValue struct {
	_            structs.HostLayout
	TotalTimeNs  uint64
	Count        uint64
	MaxTimeNs    uint64
	MinTimeNs    uint64
	SumSquaredNs uint64
}

// LoadOffcpuProfiler returns the embedded CollectionSpec for OffcpuProfiler.
func LoadOffcpuProfiler() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_OffcpuProfilerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load OffcpuProfiler: %w", err)
	}

	return spec, err
}

// LoadOffcpuProfilerObjects loads OffcpuProfiler and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*OffcpuProfilerObjects
//	*OffcpuProfilerPrograms
//	*OffcpuProfilerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadOffcpuProfilerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadOffcpuProfiler()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// OffcpuProfilerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OffcpuProfilerSpecs struct {
	OffcpuProfilerProgramSpecs
	OffcpuProfilerMapSpecs
	OffcpuProfilerVariableSpecs
}

// OffcpuProfilerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OffcpuProfilerProgramSpecs struct {
	OffcpuSchedSwitch *ebpf.ProgramSpec `ebpf:"offcpu_sched_switch"`
	TraceEpollWait    *ebpf.ProgramSpec `ebpf:"trace_epoll_wait"`
	TraceFutexWait    *ebpf.ProgramSpec `ebpf:"trace_futex_wait"`
}

// OffcpuProfilerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OffcpuProfilerMapSpecs struct {
	DebugEvents      *ebpf.MapSpec `ebpf:"debug_events"`
	MsgBufferMem     *ebpf.MapSpec `ebpf:"msg_buffer_mem"`
	OffcpuCfg        *ebpf.MapSpec `ebpf:"offcpu_cfg"`
	OffcpuCounts     *ebpf.MapSpec `ebpf:"offcpu_counts"`
	OffcpuEvents     *ebpf.MapSpec `ebpf:"offcpu_events"`
	OffcpuStacks     *ebpf.MapSpec `ebpf:"offcpu_stacks"`
	OffcpuStartTimes *ebpf.MapSpec `ebpf:"offcpu_start_times"`
	OffcpuTargetPids *ebpf.MapSpec `ebpf:"offcpu_target_pids"`
	PidCache         *ebpf.MapSpec `ebpf:"pid_cache"`
	ValidPids        *ebpf.MapSpec `ebpf:"valid_pids"`
}

// OffcpuProfilerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type OffcpuProfilerVariableSpecs struct {
	FilterPids              *ebpf.VariableSpec `ebpf:"filter_pids"`
	G_bpfDebug              *ebpf.VariableSpec `ebpf:"g_bpf_debug"`
	G_bpfHeaderPropagation  *ebpf.VariableSpec `ebpf:"g_bpf_header_propagation"`
	G_bpfTraceparentEnabled *ebpf.VariableSpec `ebpf:"g_bpf_traceparent_enabled"`
	Ip4ip6Prefix            *ebpf.VariableSpec `ebpf:"ip4ip6_prefix"`
	Unused                  *ebpf.VariableSpec `ebpf:"unused"`
	UnusedHttp2             *ebpf.VariableSpec `ebpf:"unused_http2"`
}

// OffcpuProfilerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadOffcpuProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type OffcpuProfilerObjects struct {
	OffcpuProfilerPrograms
	OffcpuProfilerMaps
	OffcpuProfilerVariables
}

func (o *OffcpuProfilerObjects) Close() error {
	return _OffcpuProfilerClose(
		&o.OffcpuProfilerPrograms,
		&o.OffcpuProfilerMaps,
	)
}

// OffcpuProfilerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadOffcpuProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type OffcpuProfilerMaps struct {
	DebugEvents      *ebpf.Map `ebpf:"debug_events"`
	MsgBufferMem     *ebpf.Map `ebpf:"msg_buffer_mem"`
	OffcpuCfg        *ebpf.Map `ebpf:"offcpu_cfg"`
	OffcpuCounts     *ebpf.Map `ebpf:"offcpu_counts"`
	OffcpuEvents     *ebpf.Map `ebpf:"offcpu_events"`
	OffcpuStacks     *ebpf.Map `ebpf:"offcpu_stacks"`
	OffcpuStartTimes *ebpf.Map `ebpf:"offcpu_start_times"`
	OffcpuTargetPids *ebpf.Map `ebpf:"offcpu_target_pids"`
	PidCache         *ebpf.Map `ebpf:"pid_cache"`
	ValidPids        *ebpf.Map `ebpf:"valid_pids"`
}

func (m *OffcpuProfilerMaps) Close() error {
	return _OffcpuProfilerClose(
		m.DebugEvents,
		m.MsgBufferMem,
		m.OffcpuCfg,
		m.OffcpuCounts,
		m.OffcpuEvents,
		m.OffcpuStacks,
		m.OffcpuStartTimes,
		m.OffcpuTargetPids,
		m.PidCache,
		m.ValidPids,
	)
}

// OffcpuProfilerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadOffcpuProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type OffcpuProfilerVariables struct {
	FilterPids              *ebpf.Variable `ebpf:"filter_pids"`
	G_bpfDebug              *ebpf.Variable `ebpf:"g_bpf_debug"`
	G_bpfHeaderPropagation  *ebpf.Variable `ebpf:"g_bpf_header_propagation"`
	G_bpfTraceparentEnabled *ebpf.Variable `ebpf:"g_bpf_traceparent_enabled"`
	Ip4ip6Prefix            *ebpf.Variable `ebpf:"ip4ip6_prefix"`
	Unused                  *ebpf.Variable `ebpf:"unused"`
	UnusedHttp2             *ebpf.Variable `ebpf:"unused_http2"`
}

// OffcpuProfilerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadOffcpuProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type OffcpuProfilerPrograms struct {
	OffcpuSchedSwitch *ebpf.Program `ebpf:"offcpu_sched_switch"`
	TraceEpollWait    *ebpf.Program `ebpf:"trace_epoll_wait"`
	TraceFutexWait    *ebpf.Program `ebpf:"trace_futex_wait"`
}

func (p *OffcpuProfilerPrograms) Close() error {
	return _OffcpuProfilerClose(
		p.OffcpuSchedSwitch,
		p.TraceEpollWait,
		p.TraceFutexWait,
	)
}

func _OffcpuProfilerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed offcpuprofiler_x86_bpfel.o
var _OffcpuProfilerBytes []byte
