// Code generated by bpf2go; DO NOT EDIT.
//go:build linux && (386 || amd64)

package profiler

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type WallProfilerSpanTiming struct {
	_                structs.HostLayout
	StartNs          uint64
	CpuStartNs       uint64
	AccumulatedCpuNs uint64
	Pid              uint32
	Tid              uint32
	OnCpu            uint8
	Pad              [7]uint8
}

type WallProfilerWallConfig struct {
	_                structs.HostLayout
	TargetPid        uint32
	_                [4]byte
	SampleIntervalNs uint64
	FilterActive     uint8
	Pad              [3]uint8
	_                [4]byte
}

type WallProfilerWallKey struct {
	_             structs.HostLayout
	Pid           uint32
	Tid           uint32
	UserStackId   int32
	KernelStackId int32
	Comm          [16]int8
}

type WallProfilerWallValue struct {
	_             structs.HostLayout
	TotalWallNs   uint64
	TotalCpuNs    uint64
	TotalOffcpuNs uint64
	Count         uint64
	MaxWallNs     uint64
	MinWallNs     uint64
}

// LoadWallProfiler returns the embedded CollectionSpec for WallProfiler.
func LoadWallProfiler() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_WallProfilerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load WallProfiler: %w", err)
	}

	return spec, err
}

// LoadWallProfilerObjects loads WallProfiler and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*WallProfilerObjects
//	*WallProfilerPrograms
//	*WallProfilerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadWallProfilerObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadWallProfiler()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// WallProfilerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type WallProfilerSpecs struct {
	WallProfilerProgramSpecs
	WallProfilerMapSpecs
	WallProfilerVariableSpecs
}

// WallProfilerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type WallProfilerProgramSpecs struct {
	ProfileWall     *ebpf.ProgramSpec `ebpf:"profile_wall"`
	TraceSpanEnd    *ebpf.ProgramSpec `ebpf:"trace_span_end"`
	TraceSpanStart  *ebpf.ProgramSpec `ebpf:"trace_span_start"`
	WallSchedSwitch *ebpf.ProgramSpec `ebpf:"wall_sched_switch"`
}

// WallProfilerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type WallProfilerMapSpecs struct {
	DebugEvents    *ebpf.MapSpec `ebpf:"debug_events"`
	MsgBufferMem   *ebpf.MapSpec `ebpf:"msg_buffer_mem"`
	PidCache       *ebpf.MapSpec `ebpf:"pid_cache"`
	SpanTimings    *ebpf.MapSpec `ebpf:"span_timings"`
	ValidPids      *ebpf.MapSpec `ebpf:"valid_pids"`
	WallCfg        *ebpf.MapSpec `ebpf:"wall_cfg"`
	WallCounts     *ebpf.MapSpec `ebpf:"wall_counts"`
	WallEvents     *ebpf.MapSpec `ebpf:"wall_events"`
	WallStacks     *ebpf.MapSpec `ebpf:"wall_stacks"`
	WallTargetPids *ebpf.MapSpec `ebpf:"wall_target_pids"`
}

// WallProfilerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type WallProfilerVariableSpecs struct {
	FilterPids              *ebpf.VariableSpec `ebpf:"filter_pids"`
	G_bpfDebug              *ebpf.VariableSpec `ebpf:"g_bpf_debug"`
	G_bpfHeaderPropagation  *ebpf.VariableSpec `ebpf:"g_bpf_header_propagation"`
	G_bpfTraceparentEnabled *ebpf.VariableSpec `ebpf:"g_bpf_traceparent_enabled"`
	Ip4ip6Prefix            *ebpf.VariableSpec `ebpf:"ip4ip6_prefix"`
	Unused                  *ebpf.VariableSpec `ebpf:"unused"`
	UnusedHttp2             *ebpf.VariableSpec `ebpf:"unused_http2"`
}

// WallProfilerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadWallProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type WallProfilerObjects struct {
	WallProfilerPrograms
	WallProfilerMaps
	WallProfilerVariables
}

func (o *WallProfilerObjects) Close() error {
	return _WallProfilerClose(
		&o.WallProfilerPrograms,
		&o.WallProfilerMaps,
	)
}

// WallProfilerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadWallProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type WallProfilerMaps struct {
	DebugEvents    *ebpf.Map `ebpf:"debug_events"`
	MsgBufferMem   *ebpf.Map `ebpf:"msg_buffer_mem"`
	PidCache       *ebpf.Map `ebpf:"pid_cache"`
	SpanTimings    *ebpf.Map `ebpf:"span_timings"`
	ValidPids      *ebpf.Map `ebpf:"valid_pids"`
	WallCfg        *ebpf.Map `ebpf:"wall_cfg"`
	WallCounts     *ebpf.Map `ebpf:"wall_counts"`
	WallEvents     *ebpf.Map `ebpf:"wall_events"`
	WallStacks     *ebpf.Map `ebpf:"wall_stacks"`
	WallTargetPids *ebpf.Map `ebpf:"wall_target_pids"`
}

func (m *WallProfilerMaps) Close() error {
	return _WallProfilerClose(
		m.DebugEvents,
		m.MsgBufferMem,
		m.PidCache,
		m.SpanTimings,
		m.ValidPids,
		m.WallCfg,
		m.WallCounts,
		m.WallEvents,
		m.WallStacks,
		m.WallTargetPids,
	)
}

// WallProfilerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadWallProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type WallProfilerVariables struct {
	FilterPids              *ebpf.Variable `ebpf:"filter_pids"`
	G_bpfDebug              *ebpf.Variable `ebpf:"g_bpf_debug"`
	G_bpfHeaderPropagation  *ebpf.Variable `ebpf:"g_bpf_header_propagation"`
	G_bpfTraceparentEnabled *ebpf.Variable `ebpf:"g_bpf_traceparent_enabled"`
	Ip4ip6Prefix            *ebpf.Variable `ebpf:"ip4ip6_prefix"`
	Unused                  *ebpf.Variable `ebpf:"unused"`
	UnusedHttp2             *ebpf.Variable `ebpf:"unused_http2"`
}

// WallProfilerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadWallProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type WallProfilerPrograms struct {
	ProfileWall     *ebpf.Program `ebpf:"profile_wall"`
	TraceSpanEnd    *ebpf.Program `ebpf:"trace_span_end"`
	TraceSpanStart  *ebpf.Program `ebpf:"trace_span_start"`
	WallSchedSwitch *ebpf.Program `ebpf:"wall_sched_switch"`
}

func (p *WallProfilerPrograms) Close() error {
	return _WallProfilerClose(
		p.ProfileWall,
		p.TraceSpanEnd,
		p.TraceSpanStart,
		p.WallSchedSwitch,
	)
}

func _WallProfilerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed wallprofiler_x86_bpfel.o
var _WallProfilerBytes []byte
