version: "2"

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  settings:
    staticcheck:
      checks:
        - all
        - -QF*    # Disable quickfix suggestions
        - -ST*    # Disable style suggestions
