
name:                     ExternalServiceOperation
query:                    api/cluster/counter/tables/external_service_op
object:                   external_service_op

counters:
  - ^^instance_uuid        => key
  - ^instance_name
  - ^node_name             => node
  - ^operation
  - ^process_name
  - ^server_ip_address
  - ^server_name
  - ^service_name
  - ^vserver_name          => svm
  - num_not_found_responses
  - num_request_failures
  - num_requests_sent
  - num_responses_received
  - num_successful_responses
  - num_timeouts
  - request_latency
  - request_latency_hist

export_options:
  instance_keys:
    - key
    - node
    - operation
    - process_name
    - server_ip_address
    - server_name
    - service_name
    - svm
