name:                     FPolicyServer
query:                    api/cluster/counter/tables/fpolicy_server
object:                   fpolicy_server

counters:
  - ^^instance_name             => instance
  - cancelled_requests           => cancelled_requests
  - failed_requests              => failed_requests
  - max_request_latency          => max_request_latency
  - outstanding_requests         => outstanding_requests
  - processed_requests           => processed_requests
  - request_latency              => request_latency

plugins:
  - LabelAgent:
      split:
        - instance `:` svm,server

export_options:
  instance_keys:
    - server
    - svm
