// Code generated by bpf2go; DO NOT EDIT.
//go:build linux && (386 || amd64)

package cudatracer

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BpfCudaEventT struct {
	_              structs.HostLayout
	TimestampNs    uint64
	DurationNs     uint64
	Pid            uint32
	Tid            uint32
	EventType      uint32
	GpuId          uint32
	StreamId       uint64
	GridDimX       uint32
	GridDimY       uint32
	GridDimZ       uint32
	BlockDimX      uint32
	BlockDimY      uint32
	BlockDimZ      uint32
	SharedMemBytes uint32
	KernelName     [128]uint8
	_              [4]byte
	SrcPtr         uint64
	DstPtr         uint64
	Bytes          uint64
	MemcpyKind     uint32
	_              [4]byte
	AllocPtr       uint64
	AllocSize      uint64
	CudaError      uint32
	Pad            uint32
}

type BpfCudaKernelInfo struct {
	_              structs.HostLayout
	StartTime      uint64
	Pid            uint32
	Tid            uint32
	GpuId          uint32
	_              [4]byte
	StreamId       uint64
	GridDimX       uint32
	GridDimY       uint32
	GridDimZ       uint32
	BlockDimX      uint32
	BlockDimY      uint32
	BlockDimZ      uint32
	SharedMemBytes uint32
	KernelName     [128]uint8
	_              [4]byte
}

type BpfCudaMemStatsT struct {
	_              structs.HostLayout
	TotalAllocated uint64
	TotalFreed     uint64
	PeakUsage      uint64
	CurrentUsage   uint64
	AllocCount     uint64
	FreeCount      uint64
}

type BpfCudaMemopInfo struct {
	_          structs.HostLayout
	StartTime  uint64
	Pid        uint32
	Tid        uint32
	SrcPtr     uint64
	DstPtr     uint64
	Bytes      uint64
	MemcpyKind uint32
	_          [4]byte
	StreamId   uint64
}

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	CudaDeviceSynchronize *ebpf.ProgramSpec `ebpf:"cudaDeviceSynchronize"`
	CudaFree              *ebpf.ProgramSpec `ebpf:"cudaFree"`
	CudaLaunchKernel      *ebpf.ProgramSpec `ebpf:"cudaLaunchKernel"`
	CudaLaunchKernelRet   *ebpf.ProgramSpec `ebpf:"cudaLaunchKernel_ret"`
	CudaMalloc            *ebpf.ProgramSpec `ebpf:"cudaMalloc"`
	CudaMemcpy            *ebpf.ProgramSpec `ebpf:"cudaMemcpy"`
	CudaMemcpyAsync       *ebpf.ProgramSpec `ebpf:"cudaMemcpyAsync"`
	CudaMemcpyRet         *ebpf.ProgramSpec `ebpf:"cudaMemcpy_ret"`
	CudaStreamCreate      *ebpf.ProgramSpec `ebpf:"cudaStreamCreate"`
	CudaStreamDestroy     *ebpf.ProgramSpec `ebpf:"cudaStreamDestroy"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	CudaActiveKernels     *ebpf.MapSpec `ebpf:"cuda_active_kernels"`
	CudaActiveMemops      *ebpf.MapSpec `ebpf:"cuda_active_memops"`
	CudaEventScratch      *ebpf.MapSpec `ebpf:"cuda_event_scratch"`
	CudaEvents            *ebpf.MapSpec `ebpf:"cuda_events"`
	CudaKernelInfoScratch *ebpf.MapSpec `ebpf:"cuda_kernel_info_scratch"`
	CudaKernelNames       *ebpf.MapSpec `ebpf:"cuda_kernel_names"`
	CudaMemPerProcess     *ebpf.MapSpec `ebpf:"cuda_mem_per_process"`
	CudaMemopScratch      *ebpf.MapSpec `ebpf:"cuda_memop_scratch"`
	DebugEvents           *ebpf.MapSpec `ebpf:"debug_events"`
	MsgBufferMem          *ebpf.MapSpec `ebpf:"msg_buffer_mem"`
	PidCache              *ebpf.MapSpec `ebpf:"pid_cache"`
	ValidPids             *ebpf.MapSpec `ebpf:"valid_pids"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
	FilterPids              *ebpf.VariableSpec `ebpf:"filter_pids"`
	G_bpfDebug              *ebpf.VariableSpec `ebpf:"g_bpf_debug"`
	G_bpfHeaderPropagation  *ebpf.VariableSpec `ebpf:"g_bpf_header_propagation"`
	G_bpfTraceparentEnabled *ebpf.VariableSpec `ebpf:"g_bpf_traceparent_enabled"`
	Ip4ip6Prefix            *ebpf.VariableSpec `ebpf:"ip4ip6_prefix"`
	Unused                  *ebpf.VariableSpec `ebpf:"unused"`
	UnusedCudaEvent         *ebpf.VariableSpec `ebpf:"unused_cuda_event"`
	UnusedCudaMemStats      *ebpf.VariableSpec `ebpf:"unused_cuda_mem_stats"`
	UnusedHttp2             *ebpf.VariableSpec `ebpf:"unused_http2"`
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	CudaActiveKernels     *ebpf.Map `ebpf:"cuda_active_kernels"`
	CudaActiveMemops      *ebpf.Map `ebpf:"cuda_active_memops"`
	CudaEventScratch      *ebpf.Map `ebpf:"cuda_event_scratch"`
	CudaEvents            *ebpf.Map `ebpf:"cuda_events"`
	CudaKernelInfoScratch *ebpf.Map `ebpf:"cuda_kernel_info_scratch"`
	CudaKernelNames       *ebpf.Map `ebpf:"cuda_kernel_names"`
	CudaMemPerProcess     *ebpf.Map `ebpf:"cuda_mem_per_process"`
	CudaMemopScratch      *ebpf.Map `ebpf:"cuda_memop_scratch"`
	DebugEvents           *ebpf.Map `ebpf:"debug_events"`
	MsgBufferMem          *ebpf.Map `ebpf:"msg_buffer_mem"`
	PidCache              *ebpf.Map `ebpf:"pid_cache"`
	ValidPids             *ebpf.Map `ebpf:"valid_pids"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.CudaActiveKernels,
		m.CudaActiveMemops,
		m.CudaEventScratch,
		m.CudaEvents,
		m.CudaKernelInfoScratch,
		m.CudaKernelNames,
		m.CudaMemPerProcess,
		m.CudaMemopScratch,
		m.DebugEvents,
		m.MsgBufferMem,
		m.PidCache,
		m.ValidPids,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
	FilterPids              *ebpf.Variable `ebpf:"filter_pids"`
	G_bpfDebug              *ebpf.Variable `ebpf:"g_bpf_debug"`
	G_bpfHeaderPropagation  *ebpf.Variable `ebpf:"g_bpf_header_propagation"`
	G_bpfTraceparentEnabled *ebpf.Variable `ebpf:"g_bpf_traceparent_enabled"`
	Ip4ip6Prefix            *ebpf.Variable `ebpf:"ip4ip6_prefix"`
	Unused                  *ebpf.Variable `ebpf:"unused"`
	UnusedCudaEvent         *ebpf.Variable `ebpf:"unused_cuda_event"`
	UnusedCudaMemStats      *ebpf.Variable `ebpf:"unused_cuda_mem_stats"`
	UnusedHttp2             *ebpf.Variable `ebpf:"unused_http2"`
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	CudaDeviceSynchronize *ebpf.Program `ebpf:"cudaDeviceSynchronize"`
	CudaFree              *ebpf.Program `ebpf:"cudaFree"`
	CudaLaunchKernel      *ebpf.Program `ebpf:"cudaLaunchKernel"`
	CudaLaunchKernelRet   *ebpf.Program `ebpf:"cudaLaunchKernel_ret"`
	CudaMalloc            *ebpf.Program `ebpf:"cudaMalloc"`
	CudaMemcpy            *ebpf.Program `ebpf:"cudaMemcpy"`
	CudaMemcpyAsync       *ebpf.Program `ebpf:"cudaMemcpyAsync"`
	CudaMemcpyRet         *ebpf.Program `ebpf:"cudaMemcpy_ret"`
	CudaStreamCreate      *ebpf.Program `ebpf:"cudaStreamCreate"`
	CudaStreamDestroy     *ebpf.Program `ebpf:"cudaStreamDestroy"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.CudaDeviceSynchronize,
		p.CudaFree,
		p.CudaLaunchKernel,
		p.CudaLaunchKernelRet,
		p.CudaMalloc,
		p.CudaMemcpy,
		p.CudaMemcpyAsync,
		p.CudaMemcpyRet,
		p.CudaStreamCreate,
		p.CudaStreamDestroy,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_x86_bpfel.o
var _BpfBytes []byte
