package exporters
// Copyright The Telegen Authors
// SPDX-License-Identifier: Apache-2.0

// Package exporters provides unified signal export capabilities.
package exporters

import (
	"context"
	"time"



















































































































































































































































}	}		},			RandomizationFactor: 0.5,			Multiplier:          1.5,			MaxElapsedTime:      5 * time.Minute,			MaxInterval:         30 * time.Second,			InitialInterval:     5 * time.Second,			Enabled:             true,		Retry: RetryConfig{		},			Timeout:      5 * time.Second,			MaxBatchSize: 1000,			Enabled:      true,		Batch: BatchConfig{		},			SamplingThereafter: 200,			SamplingInitial:    5,			Verbosity:          "normal",			Enabled:            false,		Debug: DebugConfig{		},			Namespace: "telegen",			Path:      "/metrics",			Listen:    ":9090",			Enabled:   false,		Prometheus: PrometheusConfig{		},			Profiles:    OTLPSignalConfig{Enabled: false},			Logs:        OTLPSignalConfig{Enabled: true},			Traces:      OTLPSignalConfig{Enabled: true},			Metrics:     OTLPSignalConfig{Enabled: true},			Timeout:     30 * time.Second,			Compression: "gzip",			Protocol:    "grpc",			Enabled:     true,		OTLP: OTLPConfig{	return Config{func DefaultConfig() Config {// DefaultConfig returns default exporter configuration}	RandomizationFactor float64 `mapstructure:"randomization_factor"`	// RandomizationFactor adds jitter to backoff	Multiplier float64 `mapstructure:"multiplier"`	// Multiplier is the backoff multiplier	MaxElapsedTime time.Duration `mapstructure:"max_elapsed_time"`	// MaxElapsedTime is the maximum total retry time	MaxInterval time.Duration `mapstructure:"max_interval"`	// MaxInterval is the maximum retry interval	InitialInterval time.Duration `mapstructure:"initial_interval"`	// InitialInterval is the initial retry interval	Enabled bool `mapstructure:"enabled"`	// Enabled controls whether retry is activetype RetryConfig struct {// RetryConfig holds retry configuration}	Timeout time.Duration `mapstructure:"timeout"`	// Timeout is the maximum time to wait for a batch	MaxBatchBytes int `mapstructure:"max_batch_bytes"`	// MaxBatchBytes is the maximum bytes in a batch	MaxBatchSize int `mapstructure:"max_batch_size"`	// MaxBatchSize is the maximum number of items in a batch	Enabled bool `mapstructure:"enabled"`	// Enabled controls whether batching is activetype BatchConfig struct {// BatchConfig holds batching configuration}	ServerName string `mapstructure:"server_name"`	// ServerName is the server name for verification	InsecureSkipVerify bool `mapstructure:"insecure_skip_verify"`	// InsecureSkipVerify skips server certificate verification	KeyFile string `mapstructure:"key_file"`	// KeyFile is the path to the client key	CertFile string `mapstructure:"cert_file"`	// CertFile is the path to the client certificate	CAFile string `mapstructure:"ca_file"`	// CAFile is the path to the CA certificate	Enabled bool `mapstructure:"enabled"`	// Enabled controls whether TLS is enabledtype TLSConfig struct {// TLSConfig holds TLS configuration}	SamplingThereafter int `mapstructure:"sampling_thereafter"`	// SamplingThereafter is how often to log messages after initial	SamplingInitial int `mapstructure:"sampling_initial"`	// SamplingInitial is the initial number of messages to log	Verbosity string `mapstructure:"verbosity"`	// Verbosity level (basic, normal, detailed)	Enabled bool `mapstructure:"enabled"`	// Enabled controls whether debug export is activetype DebugConfig struct {// DebugConfig holds debug exporter configuration}	Namespace string `mapstructure:"namespace"`	// Namespace for metric names	Path string `mapstructure:"path"`	// Path is the metrics path	Listen string `mapstructure:"listen"`	// Listen is the address to listen on	Enabled bool `mapstructure:"enabled"`	// Enabled controls whether Prometheus exposition is activetype PrometheusConfig struct {// PrometheusConfig holds Prometheus exporter configuration}	Headers map[string]string `mapstructure:"headers"`	// Headers overrides the main headers for this signal	Endpoint string `mapstructure:"endpoint"`	// Endpoint overrides the main endpoint for this signal	Enabled bool `mapstructure:"enabled"`	// Enabled controls whether this signal is exportedtype OTLPSignalConfig struct {// OTLPSignalConfig holds per-signal OTLP configuration}	Profiles OTLPSignalConfig `mapstructure:"profiles"`	Logs     OTLPSignalConfig `mapstructure:"logs"`	Traces   OTLPSignalConfig `mapstructure:"traces"`	Metrics  OTLPSignalConfig `mapstructure:"metrics"`	// Per-signal configuration overrides	Timeout time.Duration `mapstructure:"timeout"`	// Timeout for requests	TLS TLSConfig `mapstructure:"tls"`	// TLS configuration	Compression string `mapstructure:"compression"`	// Compression to use (gzip, none)	Headers map[string]string `mapstructure:"headers"`	// Headers to send with requests	Protocol string `mapstructure:"protocol"`	// Protocol is grpc or http	Endpoint string `mapstructure:"endpoint"`	// Endpoint is the primary OTLP endpoint	Enabled bool `mapstructure:"enabled"`	// Enabled controls whether OTLP export is activetype OTLPConfig struct {// OTLPConfig holds OTLP exporter configuration}	Retry RetryConfig `mapstructure:"retry"`	// RetryConfig for retry behavior	Batch BatchConfig `mapstructure:"batch"`	// BatchConfig for batching before export	Debug DebugConfig `mapstructure:"debug"`	// Debug configuration for debug exporter	Prometheus PrometheusConfig `mapstructure:"prometheus"`	// Prometheus configuration for metrics exposure	OTLP OTLPConfig `mapstructure:"otlp"`	// OTLP configurationtype Config struct {// Config holds unified exporter configuration}	ExportProfiles(ctx context.Context, profiles interface{}) error	// ExportProfiles exports profiling data	SignalExportertype ProfilesExporter interface {// ProfilesExporter exports profiles}	ExportLogs(ctx context.Context, logs interface{}) error	// ExportLogs exports log records	SignalExportertype LogsExporter interface {// LogsExporter exports logs}	ExportSpans(ctx context.Context, spans interface{}) error	// ExportSpans exports trace spans	SignalExportertype TracesExporter interface {// TracesExporter exports traces}	ExportMetrics(ctx context.Context, metrics interface{}) error	// ExportMetrics exports metrics with temporality configuration	SignalExportertype MetricsExporter interface {// MetricsExporter exports metrics}	Export(ctx context.Context, signals []pipeline.Signal) error	// Export exports a batch of signalstype SignalExporter interface {// SignalExporter is an interface for signal-specific exporters}	SupportedSignals() []pipeline.SignalType	// SupportedSignals returns which signal types this exporter supports	Export(ctx context.Context, signalType pipeline.SignalType, signals []pipeline.Signal) error	// Export exports signals to the destination	Stop(ctx context.Context) error	// Stop shuts down the exporter	Start(ctx context.Context) error	// Start initializes the exporter	Name() string	// Name returns the exporter nametype Exporter interface {// Exporter is the interface that all exporters must implement)	"github.com/platformbuilds/telegen/internal/pipeline"