// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

package ebpfcommon // import "github.com/mirastacklabs-ai/telegen/internal/ebpf/common"

import (
	"bufio"
	"bytes"
	"errors"
	"io"
	"log/slog"
	"net"
	"os"
	"strings"
	"sync"
	"time"
	"unsafe"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/asm"
	"github.com/cilium/ebpf/link"
	lru "github.com/hashicorp/golang-lru/v2"
	"github.com/hashicorp/golang-lru/v2/expirable"
	"github.com/hashicorp/golang-lru/v2/simplelru"

	"github.com/mirastacklabs-ai/telegen/internal/appolly/app/request"
	"github.com/mirastacklabs-ai/telegen/internal/ebpf/common/dnsparser"
	ebpfhttp "github.com/mirastacklabs-ai/telegen/internal/ebpf/common/http"
	config "github.com/mirastacklabs-ai/telegen/internal/obiconfig"
	"github.com/mirastacklabs-ai/telegen/internal/parsers/kafkaparser"
	"github.com/mirastacklabs-ai/telegen/internal/ringbuf"
	"github.com/mirastacklabs-ai/telegen/pkg/pipe/msg"
)

//go:generate $BPF2GO -cc $BPF_CLANG -cflags $BPF_CFLAGS -target amd64,arm64 -type http_request_trace_t -type sql_request_trace_t -type http_info_t -type connection_info_t -type http2_grpc_request_t -type tcp_req_t -type kafka_client_req_t -type kafka_go_req_t -type redis_client_req_t -type tcp_large_buffer_t -type otel_span_t -type mongo_go_client_req_t -type dns_req_t -type channel_link_trace_t Bpf ../../../bpf/common/common.c -- -I../../../bpf

// HTTPRequestTrace contains information from an HTTP request as directly received from the
// eBPF layer. This contains low-level C structures for accurate binary read from ring buffer.
type (
	HTTPRequestTrace     BpfHttpRequestTraceT
	SQLRequestTrace      BpfSqlRequestTraceT
	BPFHTTPInfo          BpfHttpInfoT
	BPFConnInfo          BpfConnectionInfoT
	TCPRequestInfo       BpfTcpReqT
	GoSaramaClientInfo   BpfKafkaClientReqT
	GoRedisClientInfo    BpfRedisClientReqT
	GoKafkaGoClientInfo  BpfKafkaGoReqT
	TCPLargeBufferHeader BpfTcpLargeBufferT
	GoOTelSpanTrace      BpfOtelSpanT
	GoMongoClientInfo    BpfMongoGoClientReqT
	DNSInfo              BpfDnsReqT
)

type GoChannelLinkTrace struct {
	Type       uint8
	Pad        [7]uint8
	SenderTp   tpInfo
	ReceiverTp tpInfo
}

type tpInfo struct {
	TraceId  [16]uint8
	SpanId   [8]uint8
	ParentId [8]uint8
	Ts       uint64
	Flags    uint8
	Pad      [7]uint8
}

const (
	EventTypeSQL            = 5  // EVENT_SQL_CLIENT - SQL client event
	EventTypeKHTTP          = 6  // EVENT_K_HTTP_REQUEST - HTTP Events generated by kprobes
	EventTypeKHTTP2         = 7  // EVENT_K_HTTP2_REQUEST - HTTP2/gRPC Events generated by kprobes
	EventTypeTCP            = 8  // EVENT_TCP_REQUEST - Unknown TCP protocol to be classified by user space
	EventTypeGoSarama       = 9  // EVENT_GO_KAFKA - Kafka client for Go (Shopify/IBM Sarama)
	EventTypeGoRedis        = 10 // EVENT_GO_REDIS - Redis client for Go
	EventTypeGoKafkaGo      = 11 // EVENT_GO_KAFKA_SEG - Kafka-Go client from Segment-io
	EventTypeTCPLargeBuffer = 12 // EVENT_TCP_LARGE_BUFFER - Dynamically sized TCP buffers
	EventOTelSDKGo          = 13 // EVENT_GO_SPAN - OTel SDK manual span
	EventTypeGoMongo        = 14 // EVENT_GO_MONGO - Go MongoDB spans
	EventTypeFailedConnect  = 15 // EVENT_FAILED_CONNECT - Failed Connections
	EventTypeDNS            = 16 // EVENT_DNS_REQUEST - DNS events
	EventTypeGoChannelLink  = 18 // EVENT_GO_CHANNEL_LINK - Go channel handoff span links
)

// Kernel-side classification
const (
	ProtocolTypeUnknown uint8 = iota
	ProtocolTypeMySQL
	ProtocolTypePostgres
	ProtocolTypeHTTP // not used, written for consistency
	ProtocolTypeKafka
	ProtocolTypeMQTT       // placeholder for future kernel-space detection
	ProtocolTypeAMQP       // AMQP 0-9-1 (RabbitMQ)
	ProtocolTypeCQL        // Cassandra Query Language (Cassandra/ScyllaDB)
	ProtocolTypeNATS       // NATS messaging
	ProtocolTypeMemcached  // Memcached ASCII text protocol
	ProtocolTypeClickHouse // ClickHouse native TCP protocol
	ProtocolTypeZooKeeper  // Apache ZooKeeper Jute binary protocol
	ProtocolTypeDubbo2     // Apache Dubbo2 RPC protocol
	ProtocolTypeFDB        // FoundationDB client protocol
	ProtocolTypeMSSQL      // Microsoft SQL Server (TDS)
	ProtocolTypeSunRPC     // ONC RPC over TCP
)

var IntegrityModeOverride = false

var ActiveNamespaces = make(map[uint32]uint32)

// ProbeDesc holds the information of the instrumentation points of a given
// function/symbol
type ProbeDesc struct {
	// Required, if true, will cancel the execution of the eBPF Tracer
	// if the function has not been found in the executable
	Required bool

	// The eBPF program to attach to the symbol as a uprobe (either to the
	// symbol name or to StartOffset)
	Start *ebpf.Program

	// The eBPF program to attach to the symbol either as a uretprobe or as a
	// uprobe to ReturnOffsets
	End *ebpf.Program

	// Optional offset to the start of the symbol
	StartOffset uint64

	// Optional list of the offsets of every RET instruction in the symbol
	ReturnOffsets []uint64
}

type Filter struct {
	io.Closer
	Fd int
}

type SockOps struct {
	io.Closer
	Program       *ebpf.Program
	AttachAs      ebpf.AttachType
	SockopsCgroup link.Link
}

type SockMsg struct {
	io.Closer
	Program  *ebpf.Program
	MapFD    int
	AttachAs ebpf.AttachType
}

type Iter struct {
	Program *ebpf.Program
	Link    link.Link
}

type MisclassifiedEvent struct {
	EventType int
	TCPInfo   *TCPRequestInfo
}

// CouchbaseBucketInfo holds the bucket, scope, and collection for a Couchbase connection.
type CouchbaseBucketInfo struct {
	Bucket     string
	Scope      string
	Collection string
}

type EBPFParseContext struct {
	protocolDebug              bool
	h2c                        *lru.Cache[uint64, h2Connection]
	redisDBCache               *simplelru.LRU[BpfConnectionInfoT, int]
	couchbaseBucketCache       *simplelru.LRU[BpfConnectionInfoT, CouchbaseBucketInfo]
	largeBuffers               *expirable.LRU[largeBufferKey, *largeBuffer]
	mongoRequestCache          PendingMongoDBRequests
	mysqlPreparedStatements    *simplelru.LRU[mysqlPreparedStatementsKey, string]
	postgresPreparedStatements *simplelru.LRU[postgresPreparedStatementsKey, string]
	postgresPortals            *simplelru.LRU[postgresPortalsKey, string]
	kafkaTopicUUIDToName       *simplelru.LRU[kafkaparser.UUID, string]
	payloadExtraction          config.PayloadExtraction
	httpEnricher               *ebpfhttp.HTTPEnricher
	dnsEvents                  *expirable.LRU[dnsparser.DNSId, *request.Span]
	pendingSpanLinks           *pendingSpanLinks
	emitSpans                  func([]request.Span)

	// parseStats tracks per-connection parse failure rates. When a connection's
	// failure rate exceeds parseFailureThreshold, events are suppressed.
	parseStats   map[connStatsKey]*connParseStats
	parseStatsMu sync.Mutex
}

type EBPFEventContext struct {
	CommonPIDsFilter ServiceFilter
	SharedRingBuffer *ringBufForwarder
	EBPFMaps         map[string]*ebpf.Map
	RingBufLock      sync.Mutex
	MapsLock         sync.Mutex
	LoadLock         sync.Mutex
}

var MisclassifiedEvents = make(chan MisclassifiedEvent)

func ptlog() *slog.Logger { return slog.With("component", "ebpf.ProcessTracer") }

func NewEBPFParseContext(cfg *config.EBPFTracer, spansChan *msg.Queue[[]request.Span], filter ServiceFilter) *EBPFParseContext {
	var (
		err                        error
		protocolDebug              bool
		redisDBCache               *simplelru.LRU[BpfConnectionInfoT, int]
		couchbaseBucketCache       *simplelru.LRU[BpfConnectionInfoT, CouchbaseBucketInfo]
		mysqlPreparedStatements    *simplelru.LRU[mysqlPreparedStatementsKey, string]
		postgresPreparedStatements *simplelru.LRU[postgresPreparedStatementsKey, string]
		postgresPortals            *simplelru.LRU[postgresPortalsKey, string]
		kafkaTopicUUIDToName       *simplelru.LRU[kafkaparser.UUID, string]
		mongoRequestCache          PendingMongoDBRequests
		payloadExtraction          config.PayloadExtraction
		httpEnricher               *ebpfhttp.HTTPEnricher
		dnsEvents                  *expirable.LRU[dnsparser.DNSId, *request.Span]
		emitSpans                  func([]request.Span)
	)

	h2c, _ := lru.New[uint64, h2Connection](1024 * 10)
	largeBuffers := expirable.NewLRU[largeBufferKey, *largeBuffer](1024, nil, 5*time.Minute)

	if cfg != nil {
		protocolDebug = cfg.ProtocolDebug

		if cfg.RedisDBCache.Enabled {
			redisDBCache, err = simplelru.NewLRU[BpfConnectionInfoT, int](cfg.RedisDBCache.MaxSize, nil)
			if err != nil {
				ptlog().Error("failed to create Redis DB cache", "error", err)
				redisDBCache = nil
			}
		}

		couchbaseBucketCache, err = simplelru.NewLRU[BpfConnectionInfoT, CouchbaseBucketInfo](cfg.CouchbaseDBCacheSize, nil)
		if err != nil {
			ptlog().Error("failed to create Couchbase bucket cache", "error", err)
			couchbaseBucketCache = nil
		}

		mysqlPreparedStatements, err = simplelru.NewLRU[mysqlPreparedStatementsKey, string](cfg.MySQLPreparedStatementsCacheSize, nil)
		if err != nil {
			ptlog().Error("failed to create MySQL prepared statements cache", "error", err)
		}

		postgresPreparedStatements, err = simplelru.NewLRU[postgresPreparedStatementsKey, string](cfg.PostgresPreparedStatementsCacheSize, nil)
		if err != nil {
			ptlog().Error("failed to create Postgres prepared statements cache", "error", err)
		}

		postgresPortals, err = simplelru.NewLRU[postgresPortalsKey, string](cfg.PostgresPreparedStatementsCacheSize, nil)
		if err != nil {
			ptlog().Error("failed to create Postgres portals cache", "error", err)
		}

		kafkaTopicUUIDToName, err = simplelru.NewLRU[kafkaparser.UUID, string](cfg.KafkaTopicUUIDCacheSize, nil)
		if err != nil {
			ptlog().Error("failed to create Kafka topic UUID to name cache", "error", err)
		}

		mongoRequestCache = expirable.NewLRU[MongoRequestKey, *MongoRequestValue](cfg.MongoRequestsCacheSize, nil, 0)

		payloadExtraction = cfg.PayloadExtraction
		if payloadExtraction.HTTP.Enrichment.Enabled {
			httpEnricher = ebpfhttp.NewHTTPEnricher(payloadExtraction.HTTP.Enrichment)
		}

		dnsEvents = expirable.NewLRU(1024, dnsEventExpireHandler(spansChan, filter), cfg.DNSRequestTimeout)
	}
	if spansChan != nil {
		emitSpans = func(spans []request.Span) {
			if len(spans) == 0 {
				return
			}
			if filter != nil {
				spans = filter.Filter(spans)
			}
			if len(spans) == 0 {
				return
			}
			spansChan.Send(spans)
		}
	}

	return &EBPFParseContext{
		protocolDebug:              protocolDebug,
		h2c:                        h2c,
		redisDBCache:               redisDBCache,
		couchbaseBucketCache:       couchbaseBucketCache,
		largeBuffers:               largeBuffers,
		mongoRequestCache:          mongoRequestCache,
		mysqlPreparedStatements:    mysqlPreparedStatements,
		postgresPreparedStatements: postgresPreparedStatements,
		postgresPortals:            postgresPortals,
		kafkaTopicUUIDToName:       kafkaTopicUUIDToName,
		payloadExtraction:          payloadExtraction,
		httpEnricher:               httpEnricher,
		dnsEvents:                  dnsEvents,
		parseStats:                 make(map[connStatsKey]*connParseStats),
		emitSpans:                  emitSpans,
	}
}

func NewEBPFEventContext() *EBPFEventContext {
	return &EBPFEventContext{
		EBPFMaps:    map[string]*ebpf.Map{},
		RingBufLock: sync.Mutex{},
		MapsLock:    sync.Mutex{},
		LoadLock:    sync.Mutex{},
	}
}

func ReadBPFTraceAsSpan(parseCtx *EBPFParseContext, cfg *config.EBPFTracer, record *ringbuf.Record, filter ServiceFilter) (request.Span, bool, error) {
	if len(record.RawSample) == 0 {
		return request.Span{}, true, errors.New("invalid ringbuffer record size")
	}

	eventType := record.RawSample[0]

	switch eventType {
	case EventTypeSQL:
		span, ignore, err := ReadSQLRequestTraceAsSpan(record)
		return finalizeParsedSpan(parseCtx, span, ignore, err)
	case EventTypeKHTTP:
		span, ignore, err := ReadHTTPInfoIntoSpan(parseCtx, record, filter)
		return finalizeParsedSpan(parseCtx, span, ignore, err)
	case EventTypeKHTTP2:
		span, ignore, err := ReadHTTP2InfoIntoSpan(parseCtx, record, filter)
		return finalizeParsedSpan(parseCtx, span, ignore, err)
	case EventTypeTCP:
		span, ignore, err := ReadTCPRequestIntoSpan(parseCtx, cfg, record, filter)
		return finalizeParsedSpan(parseCtx, span, ignore, err)
	case EventTypeGoSarama:
		span, ignore, err := ReadGoSaramaRequestIntoSpan(record)
		return finalizeParsedSpan(parseCtx, span, ignore, err)
	case EventTypeGoRedis:
		span, ignore, err := ReadGoRedisRequestIntoSpan(record)
		return finalizeParsedSpan(parseCtx, span, ignore, err)
	case EventTypeGoMongo:
		span, ignore, err := ReadGoMongoRequestIntoSpan(record)
		return finalizeParsedSpan(parseCtx, span, ignore, err)
	case EventTypeGoKafkaGo:
		span, ignore, err := ReadGoKafkaGoRequestIntoSpan(record)
		return finalizeParsedSpan(parseCtx, span, ignore, err)
	case EventTypeTCPLargeBuffer:
		span, ignore, err := appendTCPLargeBuffer(parseCtx, record)
		return finalizeParsedSpan(parseCtx, span, ignore, err)
	case EventOTelSDKGo:
		span, ignore, err := ReadGoOTelEventIntoSpan(record)
		return finalizeParsedSpan(parseCtx, span, ignore, err)
	case EventTypeFailedConnect:
		span, ignore, err := ReadFailedConnectIntoSpan(record, filter)
		return finalizeParsedSpan(parseCtx, span, ignore, err)
	case EventTypeDNS:
		span, ignore, err := readDNSEventIntoSpan(parseCtx, record)
		return finalizeParsedSpan(parseCtx, span, ignore, err)
	case EventTypeGoChannelLink:
		return readGoChannelLinkEvent(parseCtx, record)
	}

	event, err := ReinterpretCast[HTTPRequestTrace](record.RawSample)
	if err != nil {
		return request.Span{}, true, err
	}

	return finalizeParsedSpan(parseCtx, HTTPRequestTraceToSpan(event), false, nil)
}

func (ctx *EBPFParseContext) emitExtraSpans(spans ...request.Span) {
	if ctx == nil || len(spans) == 0 || ctx.emitSpans == nil {
		return
	}
	for i := range spans {
		ctx.consumePendingSpanLinks(&spans[i])
	}
	ctx.emitSpans(spans)
}

func finalizeParsedSpan(parseCtx *EBPFParseContext, span request.Span, ignore bool, err error) (request.Span, bool, error) {
	if err != nil || ignore {
		return span, ignore, err
	}
	if parseCtx != nil {
		parseCtx.consumePendingSpanLinks(&span)
	}
	return span, false, nil
}

func ReinterpretCast[T any](b []byte) (*T, error) {
	var zero T

	if len(b) < int(unsafe.Sizeof(zero)) {
		return nil, errors.New("byte slice too short")
	}

	return (*T)(unsafe.Pointer(unsafe.SliceData(b))), nil
}

func ReadSQLRequestTraceAsSpan(record *ringbuf.Record) (request.Span, bool, error) {
	event, err := ReinterpretCast[SQLRequestTrace](record.RawSample)
	if err != nil {
		return request.Span{}, true, err
	}

	return SQLRequestTraceToSpan(event), false, nil
}

type KernelLockdown uint8

const (
	KernelLockdownNone KernelLockdown = iota + 1
	KernelLockdownIntegrity
	KernelLockdownConfidentiality
	KernelLockdownOther
)

func SupportsLogInjection(log *slog.Logger) bool {
	kernelMajor, kernelMinor := KernelVersion()
	log.Debug("Linux kernel version", "major", kernelMajor, "minor", kernelMinor)

	if kernelMajor < 6 {
		log.Info("log injection not supported: linux kernel version < 6", "kernelMajor", kernelMajor, "kernelMinor", kernelMinor)
		return false
	}

	if !hasCapSysAdmin() {
		log.Info("log injection not supported: missing CAP_SYS_ADMIN capability")
		return false
	}

	lockdownMode := KernelLockdownMode()
	if lockdownMode != KernelLockdownNone {
		log.Info("log injection not supported: kernel in lockdown mode")
		return false
	}

	return true
}

func SupportsContextPropagationWithProbe(log *slog.Logger) bool {
	kernelMajor, kernelMinor := KernelVersion()
	log.Debug("Linux kernel version", "major", kernelMajor, "minor", kernelMinor)

	if kernelMajor < 5 || (kernelMajor == 5 && kernelMinor < 10) {
		log.Debug("Found Linux kernel earlier than 5.10, Go trace context propagation at library level is supported", "major", kernelMajor, "minor", kernelMinor)
		return true
	}

	// bpf_probe_write_user(), used to inject the context, requires CAP_SYS_ADMIN

	if !hasCapSysAdmin() {
		log.Info("Go context propagation at library level disabled due to missing capability CAP_SYS_ADMIN")
		return false
	}

	lockdown := KernelLockdownMode()

	if lockdown == KernelLockdownNone {
		log.Debug("Kernel not in lockdown mode, Go trace context propagation at library level is supported.")
		return true
	}

	return false
}

func SupportsEBPFLoops(log *slog.Logger, overrideKernelVersion bool) bool {
	if overrideKernelVersion {
		log.Debug("Skipping kernel version check for bpf_loop functionality: user supplied confirmation of support")
		return true
	}
	kernelMajor, kernelMinor := KernelVersion()
	return kernelMajor > 5 || (kernelMajor == 5 && kernelMinor >= 17)
}

func FixupSpec(spec *ebpf.CollectionSpec, overrideKernelVersion bool) {
	if !SupportsEBPFLoops(ptlog(), overrideKernelVersion) {
		// Hack: instead of redefining bpf2go generated struct for mutually exclusive conditional programs,
		// use one predefined field name to store either of them.
		spec.Programs["obi_protocol_http"] = spec.Programs["obi_protocol_http_legacy"]
		spec.Programs["obi_protocol_http"].Name = "obi_protocol_http"
	}
	// Hack: insert a dummy unused program in order to be able to use bpf2go generated struct to load
	// the collection.
	spec.Programs["obi_protocol_http_legacy"] = &ebpf.ProgramSpec{
		Name: "obi_dummy",
		Type: ebpf.Kprobe,
		Instructions: asm.Instructions{
			asm.Mov.Imm(asm.R0, 0),
			asm.Return(),
		},
		License: "MIT",
	}
}

// Injectable for tests
var lockdownPath = "/sys/kernel/security/lockdown"

func KernelLockdownMode() KernelLockdown {
	plog := ptlog()
	plog.Debug("checking kernel lockdown mode, [none] allows us to propagate trace context")
	// If we can't find the file, assume no lockdown
	if _, err := os.Stat(lockdownPath); err == nil {
		f, err := os.Open(lockdownPath)
		if err != nil {
			plog.Warn("failed to open /sys/kernel/security/lockdown, assuming lockdown [integrity]", "error", err)
			return KernelLockdownIntegrity
		}

		defer func() { _ = f.Close() }()
		scanner := bufio.NewScanner(f)
		if scanner.Scan() {
			lockdown := scanner.Text()
			switch {
			case strings.Contains(lockdown, "[none]"):
				return KernelLockdownNone
			case strings.Contains(lockdown, "[integrity]"):
				return KernelLockdownIntegrity
			case strings.Contains(lockdown, "[confidentiality]"):
				return KernelLockdownConfidentiality
			default:
				return KernelLockdownOther
			}
		}

		plog.Warn("file /sys/kernel/security/lockdown is empty, assuming lockdown [integrity]")
		return KernelLockdownIntegrity
	}

	plog.Debug("can't find /sys/kernel/security/lockdown, assuming no lockdown")
	return KernelLockdownNone
}

func cstr(chars []uint8) string {
	addrLen := bytes.IndexByte(chars, 0)
	if addrLen < 0 {
		addrLen = len(chars)
	}

	return string(chars[:addrLen])
}

func (connInfo *BPFConnInfo) reqHostInfo() (source, target string) {
	src := make(net.IP, net.IPv6len)
	dst := make(net.IP, net.IPv6len)
	copy(src, connInfo.S_addr[:])
	copy(dst, connInfo.D_addr[:])

	srcStr := src.String()
	dstStr := dst.String()

	if src.IsUnspecified() {
		srcStr = ""
	}

	if dst.IsUnspecified() {
		dstStr = ""
	}

	return srcStr, dstStr
}

func isClientEvent(et uint8) bool {
	switch request.EventType(et) {
	case request.EventTypeGRPCClient, request.EventTypeHTTPClient, request.EventTypeRedisClient,
		request.EventTypeKafkaClient, request.EventTypeSQLClient, request.EventTypeMongoClient,
		request.EventTypeFailedConnect:
		return true
	}

	return false
}

func directionByPacketType(pt uint8, isClient bool) uint8 {
	if isClient {
		if pt == packetTypeRequest {
			return directionSend
		}
		return directionRecv
	}
	if pt == packetTypeRequest {
		return directionRecv
	}
	return directionSend
}
