// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package llmtracer

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type BpfLlmEndpointKey struct {
	_    structs.HostLayout
	Host [128]uint8
	Port uint16
}

type BpfLlmEventT struct {
	_                structs.HostLayout
	TimestampNs      uint64
	DurationNs       uint64
	TtftNs           uint64
	Pid              uint32
	Tid              uint32
	EventType        uint32
	Provider         uint32
	PromptTokens     uint32
	CompletionTokens uint32
	StatusCode       uint32
	IsStreaming      uint32
	ChunkIndex       uint32
	Pad              uint32
	RequestId        [36]uint8
	Model            [128]uint8
	Endpoint         [256]uint8
	ErrorMsg         [256]uint8
	_                [4]byte
}

type BpfLlmRequest struct {
	_              structs.HostLayout
	StartTime      uint64
	FirstTokenTime uint64
	Pid            uint32
	Tid            uint32
	Provider       uint32
	IsStreaming    uint32
	ChunkCount     uint32
	RequestId      [36]uint8
	Model          [128]uint8
	Endpoint       [256]uint8
}

// LoadBpf returns the embedded CollectionSpec for Bpf.
func LoadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Bpf: %w", err)
	}

	return spec, err
}

// LoadBpfObjects loads Bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*BpfObjects
//	*BpfPrograms
//	*BpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// BpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfSpecs struct {
	BpfProgramSpecs
	BpfMapSpecs
	BpfVariableSpecs
}

// BpfProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfProgramSpecs struct {
	Http2WriteFrame       *ebpf.ProgramSpec `ebpf:"http2_write_frame"`
	HttpReadResponse      *ebpf.ProgramSpec `ebpf:"http_read_response"`
	PythonAnthropicCreate *ebpf.ProgramSpec `ebpf:"python_anthropic_create"`
	PythonOpenaiCreate    *ebpf.ProgramSpec `ebpf:"python_openai_create"`
	SseEvent              *ebpf.ProgramSpec `ebpf:"sse_event"`
}

// BpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfMapSpecs struct {
	DebugEvents       *ebpf.MapSpec `ebpf:"debug_events"`
	LlmActiveRequests *ebpf.MapSpec `ebpf:"llm_active_requests"`
	LlmEndpoints      *ebpf.MapSpec `ebpf:"llm_endpoints"`
	LlmEventScratch   *ebpf.MapSpec `ebpf:"llm_event_scratch"`
	LlmEvents         *ebpf.MapSpec `ebpf:"llm_events"`
	LlmRequestScratch *ebpf.MapSpec `ebpf:"llm_request_scratch"`
	MsgBufferMem      *ebpf.MapSpec `ebpf:"msg_buffer_mem"`
	PidCache          *ebpf.MapSpec `ebpf:"pid_cache"`
	TokenPatterns     *ebpf.MapSpec `ebpf:"token_patterns"`
	ValidPids         *ebpf.MapSpec `ebpf:"valid_pids"`
}

// BpfVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type BpfVariableSpecs struct {
	FilterPids              *ebpf.VariableSpec `ebpf:"filter_pids"`
	G_bpfDebug              *ebpf.VariableSpec `ebpf:"g_bpf_debug"`
	G_bpfHeaderPropagation  *ebpf.VariableSpec `ebpf:"g_bpf_header_propagation"`
	G_bpfTraceparentEnabled *ebpf.VariableSpec `ebpf:"g_bpf_traceparent_enabled"`
	Ip4ip6Prefix            *ebpf.VariableSpec `ebpf:"ip4ip6_prefix"`
	Unused                  *ebpf.VariableSpec `ebpf:"unused"`
	UnusedHttp2             *ebpf.VariableSpec `ebpf:"unused_http2"`
	UnusedLlmEvent          *ebpf.VariableSpec `ebpf:"unused_llm_event"`
}

// BpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfObjects struct {
	BpfPrograms
	BpfMaps
	BpfVariables
}

func (o *BpfObjects) Close() error {
	return _BpfClose(
		&o.BpfPrograms,
		&o.BpfMaps,
	)
}

// BpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfMaps struct {
	DebugEvents       *ebpf.Map `ebpf:"debug_events"`
	LlmActiveRequests *ebpf.Map `ebpf:"llm_active_requests"`
	LlmEndpoints      *ebpf.Map `ebpf:"llm_endpoints"`
	LlmEventScratch   *ebpf.Map `ebpf:"llm_event_scratch"`
	LlmEvents         *ebpf.Map `ebpf:"llm_events"`
	LlmRequestScratch *ebpf.Map `ebpf:"llm_request_scratch"`
	MsgBufferMem      *ebpf.Map `ebpf:"msg_buffer_mem"`
	PidCache          *ebpf.Map `ebpf:"pid_cache"`
	TokenPatterns     *ebpf.Map `ebpf:"token_patterns"`
	ValidPids         *ebpf.Map `ebpf:"valid_pids"`
}

func (m *BpfMaps) Close() error {
	return _BpfClose(
		m.DebugEvents,
		m.LlmActiveRequests,
		m.LlmEndpoints,
		m.LlmEventScratch,
		m.LlmEvents,
		m.LlmRequestScratch,
		m.MsgBufferMem,
		m.PidCache,
		m.TokenPatterns,
		m.ValidPids,
	)
}

// BpfVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfVariables struct {
	FilterPids              *ebpf.Variable `ebpf:"filter_pids"`
	G_bpfDebug              *ebpf.Variable `ebpf:"g_bpf_debug"`
	G_bpfHeaderPropagation  *ebpf.Variable `ebpf:"g_bpf_header_propagation"`
	G_bpfTraceparentEnabled *ebpf.Variable `ebpf:"g_bpf_traceparent_enabled"`
	Ip4ip6Prefix            *ebpf.Variable `ebpf:"ip4ip6_prefix"`
	Unused                  *ebpf.Variable `ebpf:"unused"`
	UnusedHttp2             *ebpf.Variable `ebpf:"unused_http2"`
	UnusedLlmEvent          *ebpf.Variable `ebpf:"unused_llm_event"`
}

// BpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type BpfPrograms struct {
	Http2WriteFrame       *ebpf.Program `ebpf:"http2_write_frame"`
	HttpReadResponse      *ebpf.Program `ebpf:"http_read_response"`
	PythonAnthropicCreate *ebpf.Program `ebpf:"python_anthropic_create"`
	PythonOpenaiCreate    *ebpf.Program `ebpf:"python_openai_create"`
	SseEvent              *ebpf.Program `ebpf:"sse_event"`
}

func (p *BpfPrograms) Close() error {
	return _BpfClose(
		p.Http2WriteFrame,
		p.HttpReadResponse,
		p.PythonAnthropicCreate,
		p.PythonOpenaiCreate,
		p.SseEvent,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_arm64_bpfel.o
var _BpfBytes []byte
