package semconv
// Package semconv provides OpenTelemetry semantic convention helpers for Telegen.
package semconv

import (
	"go.opentelemetry.io/otel/attribute"
	semconv "go.opentelemetry.io/otel/semconv/v1.24.0"
)

// Cloud provider constants matching OTel semantic conventions.


























































































































































































































































































































































































































































}	return pa.attrsfunc (pa *ProcessAttributes) Build() []attribute.KeyValue {// Build returns the accumulated attributes.}	return pa	}		pa.attrs = append(pa.attrs, semconv.ProcessRuntimeVersionKey.String(version))	if version != "" {func (pa *ProcessAttributes) RuntimeVersion(version string) *ProcessAttributes {// RuntimeVersion sets the runtime version.}	return pa	}		pa.attrs = append(pa.attrs, semconv.ProcessRuntimeNameKey.String(name))	if name != "" {func (pa *ProcessAttributes) RuntimeName(name string) *ProcessAttributes {// RuntimeName sets the runtime name (go, java, python, etc.).}	return pa	}		pa.attrs = append(pa.attrs, semconv.ProcessCommandLineKey.String(cmdline))	if cmdline != "" {func (pa *ProcessAttributes) CommandLine(cmdline string) *ProcessAttributes {// CommandLine sets the command line.}	return pa	}		pa.attrs = append(pa.attrs, semconv.ProcessExecutablePathKey.String(path))	if path != "" {func (pa *ProcessAttributes) ExecutablePath(path string) *ProcessAttributes {// ExecutablePath sets the executable path.}	return pa	}		pa.attrs = append(pa.attrs, semconv.ProcessExecutableNameKey.String(name))	if name != "" {func (pa *ProcessAttributes) ExecutableName(name string) *ProcessAttributes {// ExecutableName sets the executable name.}	return pa	pa.attrs = append(pa.attrs, semconv.ProcessPIDKey.Int(pid))func (pa *ProcessAttributes) PID(pid int) *ProcessAttributes {// PID sets the process ID.}	}		attrs: make([]attribute.KeyValue, 0, 8),	return &ProcessAttributes{func NewProcessAttributes() *ProcessAttributes {// NewProcessAttributes creates a new ProcessAttributes builder.}	attrs []attribute.KeyValuetype ProcessAttributes struct {// ProcessAttributes creates OTel resource attributes for a process.}	return ka.attrsfunc (ka *K8sAttributes) Build() []attribute.KeyValue {// Build returns the accumulated attributes.}	return ka	}		ka.attrs = append(ka.attrs, semconv.K8SNodeNameKey.String(name))	if name != "" {func (ka *K8sAttributes) NodeName(name string) *K8sAttributes {// NodeName sets the node name.}	return ka	}		ka.attrs = append(ka.attrs, semconv.K8SDaemonSetNameKey.String(name))	if name != "" {func (ka *K8sAttributes) DaemonSetName(name string) *K8sAttributes {// DaemonSetName sets the daemon set name.}	return ka	}		ka.attrs = append(ka.attrs, semconv.K8SStatefulSetNameKey.String(name))	if name != "" {func (ka *K8sAttributes) StatefulSetName(name string) *K8sAttributes {// StatefulSetName sets the stateful set name.}	return ka	}		ka.attrs = append(ka.attrs, semconv.K8SReplicaSetNameKey.String(name))	if name != "" {func (ka *K8sAttributes) ReplicaSetName(name string) *K8sAttributes {// ReplicaSetName sets the replica set name.}	return ka	}		ka.attrs = append(ka.attrs, semconv.K8SDeploymentNameKey.String(name))	if name != "" {func (ka *K8sAttributes) DeploymentName(name string) *K8sAttributes {// DeploymentName sets the deployment name.}	return ka	}		ka.attrs = append(ka.attrs, semconv.K8SContainerNameKey.String(name))	if name != "" {func (ka *K8sAttributes) ContainerName(name string) *K8sAttributes {// ContainerName sets the container name.}	return ka	}		ka.attrs = append(ka.attrs, semconv.K8SPodUIDKey.String(uid))	if uid != "" {func (ka *K8sAttributes) PodUID(uid string) *K8sAttributes {// PodUID sets the pod UID.}	return ka	}		ka.attrs = append(ka.attrs, semconv.K8SPodNameKey.String(name))	if name != "" {func (ka *K8sAttributes) PodName(name string) *K8sAttributes {// PodName sets the pod name.}	return ka	}		ka.attrs = append(ka.attrs, semconv.K8SNamespaceNameKey.String(ns))	if ns != "" {func (ka *K8sAttributes) Namespace(ns string) *K8sAttributes {// Namespace sets the Kubernetes namespace.}	return ka	}		ka.attrs = append(ka.attrs, semconv.K8SClusterNameKey.String(name))	if name != "" {func (ka *K8sAttributes) ClusterName(name string) *K8sAttributes {// ClusterName sets the Kubernetes cluster name.}	}		attrs: make([]attribute.KeyValue, 0, 12),	return &K8sAttributes{func NewK8sAttributes() *K8sAttributes {// NewK8sAttributes creates a new K8sAttributes builder.}	attrs []attribute.KeyValuetype K8sAttributes struct {// K8sAttributes creates OTel resource attributes for Kubernetes.}	return sa.attrsfunc (sa *ServiceAttributes) Build() []attribute.KeyValue {// Build returns the accumulated attributes.}	return sa	}		sa.attrs = append(sa.attrs, semconv.ServiceInstanceIDKey.String(id))	if id != "" {func (sa *ServiceAttributes) InstanceID(id string) *ServiceAttributes {// InstanceID sets the service instance ID.}	return sa	}		sa.attrs = append(sa.attrs, semconv.ServiceVersionKey.String(version))	if version != "" {func (sa *ServiceAttributes) Version(version string) *ServiceAttributes {// Version sets the service version.}	return sa	}		sa.attrs = append(sa.attrs, semconv.ServiceNamespaceKey.String(ns))	if ns != "" {func (sa *ServiceAttributes) Namespace(ns string) *ServiceAttributes {// Namespace sets the service namespace.}	return sa	}		sa.attrs = append(sa.attrs, semconv.ServiceNameKey.String(name))	if name != "" {func (sa *ServiceAttributes) Name(name string) *ServiceAttributes {// Name sets the service name.}	}		attrs: make([]attribute.KeyValue, 0, 8),	return &ServiceAttributes{func NewServiceAttributes() *ServiceAttributes {// NewServiceAttributes creates a new ServiceAttributes builder.}	attrs []attribute.KeyValuetype ServiceAttributes struct {// ServiceAttributes creates OTel resource attributes for a discovered service.}	return ca.attrsfunc (ca *CloudAttributes) Build() []attribute.KeyValue {// Build returns the accumulated attributes.}	return ca	}		ca.attrs = append(ca.attrs, AttrCloudHypervisor.String(hypervisor))	if hypervisor != "" {func (ca *CloudAttributes) Hypervisor(hypervisor string) *CloudAttributes {// Hypervisor sets the hypervisor type.}	return ca	}		ca.attrs = append(ca.attrs, AttrCloudClusterName.String(name))	if name != "" {func (ca *CloudAttributes) ClusterName(name string) *CloudAttributes {// ClusterName sets the cluster name.}	return ca	}		ca.attrs = append(ca.attrs, AttrCloudClusterID.String(id))	if id != "" {func (ca *CloudAttributes) ClusterID(id string) *CloudAttributes {// ClusterID sets the cluster ID.}	return ca	}		ca.attrs = append(ca.attrs, AttrCloudDatacenter.String(dc))	if dc != "" {func (ca *CloudAttributes) Datacenter(dc string) *CloudAttributes {// Datacenter sets the datacenter (private cloud).}	return ca	}		ca.attrs = append(ca.attrs, semconv.OSVersionKey.String(version))	if version != "" {func (ca *CloudAttributes) OSVersion(version string) *CloudAttributes {// OSVersion sets the operating system version.}	return ca	}		ca.attrs = append(ca.attrs, semconv.OSNameKey.String(name))	if name != "" {func (ca *CloudAttributes) OSName(name string) *CloudAttributes {// OSName sets the operating system name.}	return ca	}		ca.attrs = append(ca.attrs, semconv.OSTypeKey.String(osType))	if osType != "" {func (ca *CloudAttributes) OSType(osType string) *CloudAttributes {// OSType sets the operating system type.}	return ca	}		ca.attrs = append(ca.attrs, semconv.HostImageNameKey.String(name))	if name != "" {func (ca *CloudAttributes) HostImageName(name string) *CloudAttributes {// HostImageName sets the image name.}	return ca	}		ca.attrs = append(ca.attrs, semconv.HostImageIDKey.String(id))	if id != "" {func (ca *CloudAttributes) HostImageID(id string) *CloudAttributes {// HostImageID sets the image ID.}	return ca	}		ca.attrs = append(ca.attrs, semconv.HostArchKey.String(arch))	if arch != "" {func (ca *CloudAttributes) HostArch(arch string) *CloudAttributes {// HostArch sets the host architecture.}	return ca	}		ca.attrs = append(ca.attrs, semconv.HostTypeKey.String(hostType))	if hostType != "" {func (ca *CloudAttributes) HostType(hostType string) *CloudAttributes {// HostType sets the instance type.}	return ca	}		ca.attrs = append(ca.attrs, semconv.HostNameKey.String(name))	if name != "" {func (ca *CloudAttributes) HostName(name string) *CloudAttributes {// HostName sets the hostname.}	return ca	}		ca.attrs = append(ca.attrs, semconv.HostIDKey.String(id))	if id != "" {func (ca *CloudAttributes) HostID(id string) *CloudAttributes {// HostID sets the host/instance ID.}	return ca	}		ca.attrs = append(ca.attrs, semconv.CloudAccountIDKey.String(id))	if id != "" {func (ca *CloudAttributes) AccountID(id string) *CloudAttributes {// AccountID sets the cloud account/project ID.}	return ca	}		ca.attrs = append(ca.attrs, semconv.CloudAvailabilityZoneKey.String(zone))	if zone != "" {func (ca *CloudAttributes) AvailabilityZone(zone string) *CloudAttributes {// AvailabilityZone sets the availability zone.}	return ca	}		ca.attrs = append(ca.attrs, semconv.CloudRegionKey.String(region))	if region != "" {func (ca *CloudAttributes) Region(region string) *CloudAttributes {// Region sets the cloud region.}	return ca	ca.attrs = append(ca.attrs, semconv.CloudPlatformKey.String(platform))func (ca *CloudAttributes) Platform(platform string) *CloudAttributes {// Platform sets the cloud platform.}	return ca	ca.attrs = append(ca.attrs, semconv.CloudProviderKey.String(provider))func (ca *CloudAttributes) Provider(provider string) *CloudAttributes {// Provider sets the cloud provider.}	}		attrs: make([]attribute.KeyValue, 0, 16),	return &CloudAttributes{func NewCloudAttributes() *CloudAttributes {// NewCloudAttributes creates a new CloudAttributes builder.}	attrs []attribute.KeyValuetype CloudAttributes struct {// CloudAttributes creates OTel resource attributes for a cloud environment.)	AttrNetworkDNSServers    = attribute.Key("network.dns.servers")	AttrNetworkGateway       = attribute.Key("network.gateway")	AttrNetworkInterfaceType = attribute.Key("network.interface.type")	AttrNetworkInterfaceName = attribute.Key("network.interface.name")	// Network discovery attributes	AttrMQPort    = attribute.Key("messaging.port")	AttrMQVersion = attribute.Key("messaging.version")	AttrMQType    = attribute.Key("messaging.type")	// Message queue discovery attributes	AttrDatabasePort    = attribute.Key("db.port")	AttrDatabaseVersion = attribute.Key("db.version")	AttrDatabaseType    = attribute.Key("db.type")	// Database discovery attributes	AttrProcessType         = attribute.Key("process.type")	AttrProcessFrameworkVer = attribute.Key("process.framework.version")	AttrProcessFramework    = attribute.Key("process.framework")	AttrProcessLanguage     = attribute.Key("process.language")	// Process discovery attributes	AttrContainerRuntimeVersion = attribute.Key("container.runtime.version")	AttrContainerRuntimeName    = attribute.Key("container.runtime.name")	// Container runtime attributes	AttrVirtualizationIsVM = attribute.Key("virtualization.is_vm")	AttrVirtualizationType = attribute.Key("virtualization.type")	// Virtualization attributes	AttrCloudHostName         = attribute.Key("cloud.host.name")	AttrCloudHostID           = attribute.Key("cloud.host.id")	AttrCloudHypervisor       = attribute.Key("cloud.hypervisor")	AttrCloudResourcePoolName = attribute.Key("cloud.resource_pool.name")	AttrCloudResourcePoolID   = attribute.Key("cloud.resource_pool.id")	AttrCloudClusterName      = attribute.Key("cloud.cluster.name")	AttrCloudClusterID        = attribute.Key("cloud.cluster.id")	AttrCloudDatacenter       = attribute.Key("cloud.datacenter")	// Cloud attributes beyond standard semconvvar (// Custom attribute keys for Telegen.const TelegenNamespace = "telegen"// Service namespace for Telegen-specific attributes.)	CloudPlatformOnPrem           = "on_premises"	CloudPlatformNutanixAHV       = "nutanix_ahv"	CloudPlatformVMwarevSphere    = "vmware_vsphere"	CloudPlatformOpenStackNova    = "openstack_nova"	CloudPlatformAzureFunctions   = "azure_functions"	CloudPlatformAzureAKS         = "azure_aks"	CloudPlatformAzureVM          = "azure_vm"	CloudPlatformGCPCloudRun      = "gcp_cloud_run"	CloudPlatformGCPGKE           = "gcp_kubernetes_engine"	CloudPlatformGCPComputeEngine = "gcp_compute_engine"	CloudPlatformAWSECS           = "aws_ecs"	CloudPlatformAWSLambda        = "aws_lambda"	CloudPlatformAWSEKS           = "aws_eks"	CloudPlatformAWSEC2           = "aws_ec2"const (// Cloud platform constants.)	CloudProviderOnPrem       = "on_premises"	CloudProviderNutanix      = "nutanix"	CloudProviderVMware       = "vmware"	CloudProviderOpenStack    = "openstack"	CloudProviderDigitalOcean = "digitalocean"	CloudProviderOracleCloud  = "oracle_cloud"	CloudProviderAlibabaCloud = "alibaba_cloud"	CloudProviderAzure        = "azure"	CloudProviderGCP          = "gcp"	CloudProviderAWS          = "aws"const (