{{/*
Telegen v2.0 Helm Template Helpers
Task: DEP-009
Fully loaded configuration generator
*/}}

{{/*
Expand the name of the chart.
*/}}
{{- define "telegen.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
*/}}
{{- define "telegen.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "telegen.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "telegen.labels" -}}
helm.sh/chart: {{ include "telegen.chart" . }}
{{ include "telegen.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
app.kubernetes.io/part-of: observability
{{- end }}

{{/*
Selector labels
*/}}
{{- define "telegen.selectorLabels" -}}
app.kubernetes.io/name: {{ include "telegen.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Create the name of the service account to use
*/}}
{{- define "telegen.serviceAccountName" -}}
{{- if .Values.serviceAccount.create }}
{{- default (include "telegen.fullname" .) .Values.serviceAccount.name }}
{{- else }}
{{- default "default" .Values.serviceAccount.name }}
{{- end }}
{{- end }}

{{/*
Namespace helper
*/}}
{{- define "telegen.namespace" -}}
{{- default .Release.Namespace .Values.namespaceOverride }}
{{- end }}

{{/*
Generate OTLP endpoint configuration
*/}}
{{- define "telegen.otlpEndpoint" -}}
{{- if .Values.otlp.endpoint }}
{{- .Values.otlp.endpoint }}
{{- else }}
otel-collector:4317
{{- end }}
{{- end }}

{{/*
Generate the fully loaded agent configuration
*/}}
{{- define "telegen.config" -}}
{{- if .Values.configOverride }}
{{ .Values.configOverride }}
{{- else }}
# =============================================================================
# Telegen v2.0 Agent Configuration (Generated by Helm)
# =============================================================================

# -----------------------------------------------------------------------------
# Core Agent Configuration
# -----------------------------------------------------------------------------
agent:
  service_name: {{ .Values.agent.serviceName | default "telegen" | quote }}
  instance_id: "${NODE_NAME}"
  mode: {{ .Values.mode }}
  log_level: {{ .Values.agent.logLevel | default "INFO" }}
  log_format: {{ .Values.agent.logFormat | default "json" }}
  shutdown_timeout: {{ .Values.agent.shutdownTimeout | default "10s" }}
  enforce_sys_caps: {{ .Values.agent.enforceSysCaps | default false }}

# -----------------------------------------------------------------------------
# Self-Telemetry Configuration
# -----------------------------------------------------------------------------
selfTelemetry:
  listen: ":{{ .Values.selfTelemetry.listen | default .Values.service.port | default 19090 }}"
  health_listen: ":{{ .Values.selfTelemetry.healthListen | default .Values.service.healthPort | default 8080 }}"
  prometheus_namespace: {{ .Values.selfTelemetry.prometheusNamespace | default "telegen" | quote }}
  pprof_enabled: {{ .Values.selfTelemetry.pprofEnabled | default false }}
  pprof_port: {{ .Values.selfTelemetry.pprofPort | default 6060 }}

# -----------------------------------------------------------------------------
# Internal Metrics Configuration
# -----------------------------------------------------------------------------
internal_metrics:
  exporter: {{ .Values.internalMetrics.exporter | default "disabled" }}
  prometheus:
    port: {{ .Values.internalMetrics.prometheus.port | default 0 }}
    path: {{ .Values.internalMetrics.prometheus.path | default "/internal/metrics" | quote }}
  bpf_metric_scrape_interval: {{ .Values.internalMetrics.bpfMetricScrapeInterval | default "15s" }}

# -----------------------------------------------------------------------------
# eBPF Tracer Configuration
# -----------------------------------------------------------------------------
ebpf:
  enabled: {{ .Values.ebpf.enabled | default true }}
  batch_length: {{ .Values.ebpf.batchLength | default 100 }}
  batch_timeout: {{ .Values.ebpf.batchTimeout | default "1s" }}
  http_request_timeout: {{ .Values.ebpf.httpRequestTimeout | default "0s" }}
  dns_request_timeout: {{ .Values.ebpf.dnsRequestTimeout | default "5s" }}
  max_transaction_time: {{ .Values.ebpf.maxTransactionTime | default "5m" }}
  tc_backend: {{ .Values.ebpf.tcBackend | default "auto" }}
  context_propagation: {{ .Values.ebpf.contextPropagation | default "disabled" }}
  buffer_sizes:
    http: {{ .Values.ebpf.bufferSizes.http | default 0 }}
    mysql: {{ .Values.ebpf.bufferSizes.mysql | default 0 }}
    postgres: {{ .Values.ebpf.bufferSizes.postgres | default 0 }}
    kafka: {{ .Values.ebpf.bufferSizes.kafka | default 0 }}
  ringbuf_size: {{ .Values.ebpf.ringbufSize | default 262144 }}
  perf_buffer_size: {{ .Values.ebpf.perfBufferSize | default 8192 }}
  bpf_fs: {{ .Values.ebpf.bpfFs | default "/sys/fs/bpf" | quote }}
  pin_objects: {{ .Values.ebpf.pinObjects | default false }}
  mysql_prepared_statements_cache_size: {{ .Values.ebpf.mysqlPreparedStatementsCacheSize | default 1024 }}
  postgres_prepared_statements_cache_size: {{ .Values.ebpf.postgresPreparedStatementsCacheSize | default 1024 }}
  mongo_requests_cache_size: {{ .Values.ebpf.mongoRequestsCacheSize | default 1024 }}
  kafka_topic_uuid_cache_size: {{ .Values.ebpf.kafkaTopicUuidCacheSize | default 1024 }}
  couchbase_db_cache_size: {{ .Values.ebpf.couchbaseDbCacheSize | default 1024 }}
  redis_db_cache:
    enabled: {{ .Values.ebpf.redisDbCache.enabled | default false }}
    max_size: {{ .Values.ebpf.redisDbCache.maxSize | default 1000 }}
  override_bpf_loop_enabled: {{ .Values.ebpf.overrideBpfLoopEnabled | default false }}
  payload_extraction:
    http:
      graphql:
        enabled: {{ .Values.ebpf.payloadExtraction.http.graphql.enabled | default false }}
      elasticsearch:
        enabled: {{ .Values.ebpf.payloadExtraction.http.elasticsearch.enabled | default false }}
      aws:
        enabled: {{ .Values.ebpf.payloadExtraction.http.aws.enabled | default false }}
  log_enricher:
    cache_ttl: {{ .Values.ebpf.logEnricher.cacheTtl | default "30m" }}
    cache_size: {{ .Values.ebpf.logEnricher.cacheSize | default 128 }}
    async_writer_workers: {{ .Values.ebpf.logEnricher.asyncWriterWorkers | default 8 }}
    async_writer_channel_len: {{ .Values.ebpf.logEnricher.asyncWriterChannelLen | default 500 }}

# -----------------------------------------------------------------------------
# Channel Configuration
# -----------------------------------------------------------------------------
channel_buffer_len: {{ .Values.channel.bufferLen | default 50 }}
channel_send_timeout: {{ .Values.channel.sendTimeout | default "1m" }}
channel_send_timeout_panic: {{ .Values.channel.sendTimeoutPanic | default false }}

# -----------------------------------------------------------------------------
# Network Observability Configuration
# -----------------------------------------------------------------------------
network:
  enabled: {{ .Values.network.enabled | default true }}
  capture:
    enabled: {{ .Values.network.capture.enabled | default true }}
    interfaces: {{ .Values.network.capture.interfaces | default list | toJson }}
    exclude_loopback: {{ .Values.network.capture.excludeLoopback | default true }}
    bpf_filter: {{ .Values.network.capture.bpfFilter | default "" | quote }}
  dns:
    enabled: {{ .Values.network.dns.enabled | default true }}
    cache_size: {{ .Values.network.dns.cacheSize | default 10000 }}
    capture_queries: {{ .Values.network.dns.captureQueries | default true }}
    capture_responses: {{ .Values.network.dns.captureResponses | default true }}
  tcp:
    enabled: {{ .Values.network.tcp.enabled | default true }}
    state_tracking: {{ .Values.network.tcp.stateTracking | default true }}
    retransmissions: {{ .Values.network.tcp.retransmissions | default true }}
    rtt: {{ .Values.network.tcp.rtt | default true }}
  aggregation:
    interval: {{ .Values.network.aggregation.interval | default "30s" }}
    max_flows: {{ .Values.network.aggregation.maxFlows | default 100000 }}
  protocols:
    http:
      enabled: {{ .Values.network.protocols.http.enabled | default true }}
      parse_headers: {{ .Values.network.protocols.http.parseHeaders | default true }}
      max_body_size: {{ .Values.network.protocols.http.maxBodySize | default 65536 }}
    grpc:
      enabled: {{ .Values.network.protocols.grpc.enabled | default true }}
    mysql:
      enabled: {{ .Values.network.protocols.mysql.enabled | default true }}
      capture_query: {{ .Values.network.protocols.mysql.captureQuery | default true }}
    postgres:
      enabled: {{ .Values.network.protocols.postgres.enabled | default true }}
      capture_query: {{ .Values.network.protocols.postgres.captureQuery | default true }}
    redis:
      enabled: {{ .Values.network.protocols.redis.enabled | default true }}
      capture_command: {{ .Values.network.protocols.redis.captureCommand | default true }}
    mongodb:
      enabled: {{ .Values.network.protocols.mongodb.enabled | default true }}
      capture_query: {{ .Values.network.protocols.mongodb.captureQuery | default true }}
    kafka:
      enabled: {{ .Values.network.protocols.kafka.enabled | default true }}
    rabbitmq:
      enabled: {{ .Values.network.protocols.rabbitmq.enabled | default true }}
    mqtt:
      enabled: {{ .Values.network.protocols.mqtt.enabled | default true }}
    dns:
      enabled: {{ .Values.network.protocols.dns.enabled | default true }}

# -----------------------------------------------------------------------------
# Discovery Configuration
# -----------------------------------------------------------------------------
discovery:
  exclude_otel_instrumented_services: {{ .Values.discovery.excludeOtelInstrumentedServices | default true }}
  exclude_otel_instrumented_services_span_metrics: {{ .Values.discovery.excludeOtelInstrumentedServicesSpanMetrics | default false }}
  instrument:
    {{- range .Values.discovery.instrument | default (list (dict "path" "*")) }}
    - path: {{ .path | quote }}
    {{- end }}
  min_process_age: {{ .Values.discovery.minProcessAge | default "5s" }}
  default_otlp_grpc_port: {{ .Values.discovery.defaultOtlpGrpcPort | default 4317 }}
  route_harvester_timeout: {{ .Values.discovery.routeHarvesterTimeout | default "10s" }}
  disabled_route_harvesters: {{ .Values.discovery.disabledRouteHarvesters | default list | toJson }}
  route_harvester_advanced:
    java_harvest_delay: {{ .Values.discovery.routeHarvesterAdvanced.javaHarvestDelay | default "60s" }}

# -----------------------------------------------------------------------------
# Kubernetes Attributes Configuration
# -----------------------------------------------------------------------------
attributes:
  instance_id:
    hostname_dns_resolution: {{ .Values.attributes.instanceId.hostnameDnsResolution | default true }}
  kubernetes:
    enable: {{ .Values.attributes.kubernetes.enable | default true }}
    informers_sync_timeout: {{ .Values.attributes.kubernetes.informersSyncTimeout | default "30s" }}
    informers_resync_period: {{ .Values.attributes.kubernetes.informersResyncPeriod | default "30m" }}
    resource_labels:
      {{- range .Values.attributes.kubernetes.resourceLabels | default (list "app" "app.kubernetes.io/name" "app.kubernetes.io/component") }}
      - {{ . }}
      {{- end }}
  host_id:
    fetch_timeout: {{ .Values.attributes.hostId.fetchTimeout | default "500ms" }}
  rename_unresolved_hosts: {{ .Values.attributes.renameUnresolvedHosts | default "unresolved" | quote }}
  rename_unresolved_hosts_outgoing: {{ .Values.attributes.renameUnresolvedHostsOutgoing | default "outgoing" | quote }}
  rename_unresolved_hosts_incoming: {{ .Values.attributes.renameUnresolvedHostsIncoming | default "incoming" | quote }}
  metric_span_name_aggregation_limit: {{ .Values.attributes.metricSpanNameAggregationLimit | default 100 }}

# -----------------------------------------------------------------------------
# Profiling Configuration
# -----------------------------------------------------------------------------
profiling:
  enabled: {{ .Values.profiling.enabled | default true }}
  cpu:
    enabled: {{ .Values.profiling.cpu.enabled | default true }}
    sample_rate: {{ .Values.profiling.cpu.sampleRate | default 99 }}
    max_stack_depth: {{ .Values.profiling.cpu.maxStackDepth | default 127 }}
  off_cpu:
    enabled: {{ .Values.profiling.offCpu.enabled | default true }}
    min_block_time_ns: {{ .Values.profiling.offCpu.minBlockTimeNs | default 1000000 }}
  memory:
    enabled: {{ .Values.profiling.memory.enabled | default true }}
    min_alloc_size: {{ .Values.profiling.memory.minAllocSize | default 1024 }}
  mutex:
    enabled: {{ .Values.profiling.mutex.enabled | default true }}
    contention_threshold_ns: {{ .Values.profiling.mutex.contentionThresholdNs | default 1000000 }}
  wall:
    enabled: {{ .Values.profiling.wall.enabled | default false }}
  collection_interval: {{ .Values.profiling.collectionInterval | default "10s" }}
  target_pid: {{ .Values.profiling.targetPid | default 0 }}
  target_pids: {{ .Values.profiling.targetPids | default list | toJson }}
  target_container_ids: {{ .Values.profiling.targetContainerIds | default list | toJson }}
  exclude_kernel: {{ .Values.profiling.excludeKernel | default false }}
  exclude_user: {{ .Values.profiling.excludeUser | default false }}
  symbols:
    cache_size: {{ .Values.profiling.symbols.cacheSize | default 10000 }}
    debug_info_enabled: {{ .Values.profiling.symbols.debugInfoEnabled | default true }}
    demangling_enabled: {{ .Values.profiling.symbols.demanglingEnabled | default true }}
    go_symbols: {{ .Values.profiling.symbols.goSymbols | default true }}
    kernel_symbols: {{ .Values.profiling.symbols.kernelSymbols | default true }}
  output_format: {{ .Values.profiling.outputFormat | default "pprof" }}
  aggregate_stacks: {{ .Values.profiling.aggregateStacks | default true }}
  upload_interval: {{ .Values.profiling.uploadInterval | default "60s" }}

# -----------------------------------------------------------------------------
# Security Observability Configuration
# -----------------------------------------------------------------------------
security:
  enabled: {{ .Values.security.enabled | default true }}
  syscall_audit:
    enabled: {{ .Values.security.syscallAudit.enabled | default true }}
    syscalls: {{ .Values.security.syscallAudit.syscalls | default list | toJson }}
    exclude_processes:
      {{- range .Values.security.syscallAudit.excludeProcesses | default (list "telegen" "kubelet" "containerd") }}
      - {{ . }}
      {{- end }}
    exclude_uids: {{ .Values.security.syscallAudit.excludeUids | default list | toJson }}
    capture_args: {{ .Values.security.syscallAudit.captureArgs | default true }}
    capture_execve_args: {{ .Values.security.syscallAudit.captureExecveArgs | default true }}
  file_integrity:
    enabled: {{ .Values.security.fileIntegrity.enabled | default true }}
    sensitive_paths:
      {{- range .Values.security.fileIntegrity.sensitivePaths | default (list "/etc/passwd" "/etc/shadow" "/etc/sudoers") }}
      - {{ . }}
      {{- end }}
    exclude_paths:
      {{- range .Values.security.fileIntegrity.excludePaths | default (list "/var/log" "/tmp") }}
      - {{ . }}
      {{- end }}
    monitor_writes: {{ .Values.security.fileIntegrity.monitorWrites | default true }}
    monitor_deletes: {{ .Values.security.fileIntegrity.monitorDeletes | default true }}
    monitor_renames: {{ .Values.security.fileIntegrity.monitorRenames | default true }}
    monitor_permissions: {{ .Values.security.fileIntegrity.monitorPermissions | default true }}
    monitor_ownership: {{ .Values.security.fileIntegrity.monitorOwnership | default true }}
  container_escape:
    enabled: {{ .Values.security.containerEscape.enabled | default true }}
    alert_on_all_caps: {{ .Values.security.containerEscape.alertOnAllCaps | default false }}
    monitor_mounts: {{ .Values.security.containerEscape.monitorMounts | default true }}
    monitor_namespaces: {{ .Values.security.containerEscape.monitorNamespaces | default true }}
    monitor_modules: {{ .Values.security.containerEscape.monitorModules | default true }}
    dangerous_capabilities:
      {{- range .Values.security.containerEscape.dangerousCapabilities | default (list "CAP_SYS_ADMIN" "CAP_SYS_PTRACE" "CAP_NET_ADMIN") }}
      - {{ . }}
      {{- end }}
  alerting:
    min_severity: {{ .Values.security.alerting.minSeverity | default "high" }}
    destinations:
      {{- range .Values.security.alerting.destinations | default (list (dict "type" "log")) }}
      - type: {{ .type }}
      {{- end }}
    rate_limiting:
      enabled: {{ .Values.security.alerting.rateLimiting.enabled | default true }}
      max_alerts_per_min: {{ .Values.security.alerting.rateLimiting.maxAlertsPerMin | default 100 }}
      burst_size: {{ .Values.security.alerting.rateLimiting.burstSize | default 20 }}
  export:
    format: {{ .Values.security.export.format | default "otlp_logs" }}
    endpoint: {{ .Values.security.export.endpoint | default "" | quote }}
    batch_size: {{ .Values.security.export.batchSize | default 100 }}
    flush_interval_ms: {{ .Values.security.export.flushIntervalMs | default 5000 }}

# -----------------------------------------------------------------------------
# Database Tracing Configuration
# -----------------------------------------------------------------------------
database_tracing:
  enabled: {{ .Values.databaseTracing.enabled | default true }}
  postgresql:
    enabled: {{ .Values.databaseTracing.postgresql.enabled | default true }}
    capture_query: {{ .Values.databaseTracing.postgresql.captureQuery | default true }}
    max_query_length: {{ .Values.databaseTracing.postgresql.maxQueryLength | default 2048 }}
    capture_errors: {{ .Values.databaseTracing.postgresql.captureErrors | default true }}
    prune_sensitive: {{ .Values.databaseTracing.postgresql.pruneSensitive | default true }}
    track_prepared: {{ .Values.databaseTracing.postgresql.trackPrepared | default true }}
    slow_query_threshold: {{ .Values.databaseTracing.postgresql.slowQueryThreshold | default "1s" }}
  mysql:
    enabled: {{ .Values.databaseTracing.mysql.enabled | default true }}
    capture_query: {{ .Values.databaseTracing.mysql.captureQuery | default true }}
    max_query_length: {{ .Values.databaseTracing.mysql.maxQueryLength | default 2048 }}
    capture_errors: {{ .Values.databaseTracing.mysql.captureErrors | default true }}
    prune_sensitive: {{ .Values.databaseTracing.mysql.pruneSensitive | default true }}
    track_prepared: {{ .Values.databaseTracing.mysql.trackPrepared | default true }}
    slow_query_threshold: {{ .Values.databaseTracing.mysql.slowQueryThreshold | default "1s" }}
  oracle:
    enabled: {{ .Values.databaseTracing.oracle.enabled | default true }}
    capture_sql: {{ .Values.databaseTracing.oracle.captureSql | default true }}
    capture_plsql: {{ .Values.databaseTracing.oracle.capturePlsql | default true }}
    capture_wait_events: {{ .Values.databaseTracing.oracle.captureWaitEvents | default true }}
    max_sql_length: {{ .Values.databaseTracing.oracle.maxSqlLength | default 2048 }}
    slow_query_threshold: {{ .Values.databaseTracing.oracle.slowQueryThreshold | default "2s" }}
  kafka:
    enabled: {{ .Values.databaseTracing.kafka.enabled | default true }}
    capture_headers: {{ .Values.databaseTracing.kafka.captureHeaders | default true }}
    track_consumer_lag: {{ .Values.databaseTracing.kafka.trackConsumerLag | default true }}
    capture_topic_info: {{ .Values.databaseTracing.kafka.captureTopicInfo | default true }}
  redis:
    enabled: {{ .Values.databaseTracing.redis.enabled | default true }}
    capture_keys: {{ .Values.databaseTracing.redis.captureKeys | default true }}
    max_key_length: {{ .Values.databaseTracing.redis.maxKeyLength | default 256 }}
    track_hot_keys: {{ .Values.databaseTracing.redis.trackHotKeys | default true }}
    max_hot_keys: {{ .Values.databaseTracing.redis.maxHotKeys | default 10000 }}
    slow_command_threshold: {{ .Values.databaseTracing.redis.slowCommandThreshold | default "100ms" }}

# -----------------------------------------------------------------------------
# Query Statistics Configuration
# -----------------------------------------------------------------------------
stats:
  enabled: {{ .Values.stats.enabled | default true }}
  aggregation_interval: {{ .Values.stats.aggregationInterval | default "10s" }}
  max_patterns: {{ .Values.stats.maxPatterns | default 10000 }}
  calculate_percentiles: {{ .Values.stats.calculatePercentiles | default true }}
  percentiles: {{ .Values.stats.percentiles | default (list 50 90 95 99) | toJson }}

# -----------------------------------------------------------------------------
# Slow Query Detection Configuration
# -----------------------------------------------------------------------------
slow_queries:
  enabled: {{ .Values.slowQueries.enabled | default true }}
  default_threshold: {{ .Values.slowQueries.defaultThreshold | default "1s" }}
  thresholds:
    postgresql: {{ .Values.slowQueries.thresholds.postgresql | default "1s" }}
    mysql: {{ .Values.slowQueries.thresholds.mysql | default "1s" }}
    oracle: {{ .Values.slowQueries.thresholds.oracle | default "2s" }}
    redis: {{ .Values.slowQueries.thresholds.redis | default "100ms" }}
    kafka: {{ .Values.slowQueries.thresholds.kafka | default "500ms" }}
  max_retained: {{ .Values.slowQueries.maxRetained | default 1000 }}
  alert_very_slow: {{ .Values.slowQueries.alertVerySlow | default true }}
  alert_repeated: {{ .Values.slowQueries.alertRepeated | default true }}
  repeated_min_count: {{ .Values.slowQueries.repeatedMinCount | default 5 }}

# -----------------------------------------------------------------------------
# Language-Specific Instrumentation
# -----------------------------------------------------------------------------
nodejs:
  enabled: {{ .Values.nodejs.enabled | default true }}

javaagent:
  enabled: {{ .Values.javaagent.enabled | default true }}
  timeout: {{ .Values.javaagent.timeout | default "10s" }}

# -----------------------------------------------------------------------------
# Cloud Provider Configuration
# -----------------------------------------------------------------------------
cloud:
  auto_detect: {{ .Values.cloud.autoDetect | default true }}
  detection_timeout: {{ .Values.cloud.detectionTimeout | default "10s" }}
  detection_interval: {{ .Values.cloud.detectionInterval | default "5m" }}
  collect_metrics: {{ .Values.cloud.collectMetrics | default true }}
  metrics_interval: {{ .Values.cloud.metricsInterval | default "30s" }}
  discover_resources: {{ .Values.cloud.discoverResources | default true }}
  resource_interval: {{ .Values.cloud.resourceInterval | default "5m" }}
  aws:
    enabled: {{ .Values.cloud.aws.enabled | default true }}
    timeout: {{ .Values.cloud.aws.timeout | default "200ms" }}
    refresh_interval: {{ .Values.cloud.aws.refreshInterval | default "15m" }}
    collect_tags: {{ .Values.cloud.aws.collectTags | default false }}
    tag_allowlist: {{ .Values.cloud.aws.tagAllowlist | default list | toJson }}
    region: {{ .Values.cloud.aws.region | default "" | quote }}
    imdsv2_only: {{ .Values.cloud.aws.imdsv2Only | default true }}
    imds_endpoint: {{ .Values.cloud.aws.imdsEndpoint | default "" | quote }}
    imds_timeout: {{ .Values.cloud.aws.imdsTimeout | default "2s" }}
  gcp:
    enabled: {{ .Values.cloud.gcp.enabled | default true }}
    project: {{ .Values.cloud.gcp.project | default "" | quote }}
    zone: {{ .Values.cloud.gcp.zone | default "" | quote }}
    metadata_endpoint: {{ .Values.cloud.gcp.metadataEndpoint | default "" | quote }}
    metadata_timeout: {{ .Values.cloud.gcp.metadataTimeout | default "2s" }}
  azure:
    enabled: {{ .Values.cloud.azure.enabled | default true }}
    subscription_id: {{ .Values.cloud.azure.subscriptionId | default "" | quote }}
    resource_group: {{ .Values.cloud.azure.resourceGroup | default "" | quote }}
    imds_endpoint: {{ .Values.cloud.azure.imdsEndpoint | default "" | quote }}
    imds_timeout: {{ .Values.cloud.azure.imdsTimeout | default "2s" }}

# -----------------------------------------------------------------------------
# Name Resolver Configuration
# -----------------------------------------------------------------------------
name_resolver:
  sources:
    {{- range .Values.nameResolver.sources | default (list "host" "k8s") }}
    - {{ . }}
    {{- end }}
  cache_len: {{ .Values.nameResolver.cacheLen | default 1024 }}
  cache_ttl: {{ .Values.nameResolver.cacheTtl | default "5m" }}

# -----------------------------------------------------------------------------
# Routes Configuration
# -----------------------------------------------------------------------------
routes:
  unmatch: {{ .Values.routes.unmatch | default "heuristic" }}
  wildcard_char: {{ .Values.routes.wildcardChar | default "*" | quote }}
  max_path_segment_cardinality: {{ .Values.routes.maxPathSegmentCardinality | default 10 }}
  patterns: {{ .Values.routes.patterns | default list | toJson }}

# -----------------------------------------------------------------------------
# Filter Configuration
# -----------------------------------------------------------------------------
filter:
  application:
    by_attribute: {{ .Values.filter.application.byAttribute | default list | toJson }}
  network:
    by_attribute: {{ .Values.filter.network.byAttribute | default list | toJson }}

# -----------------------------------------------------------------------------
# Queues Configuration
# -----------------------------------------------------------------------------
queues:
  traces:
    mem_limit: {{ .Values.queues.traces.memLimit | default "256Mi" | quote }}
    max_age: {{ .Values.queues.traces.maxAge | default "6h" | quote }}
  logs:
    mem_limit: {{ .Values.queues.logs.memLimit | default "256Mi" | quote }}
    max_age: {{ .Values.queues.logs.maxAge | default "24h" | quote }}
  metrics:
    mem_limit: {{ .Values.queues.metrics.memLimit | default "128Mi" | quote }}
    max_age: {{ .Values.queues.metrics.maxAge | default "5m" | quote }}

# -----------------------------------------------------------------------------
# Backoff Configuration
# -----------------------------------------------------------------------------
backoff:
  initial: {{ .Values.backoff.initial | default "500ms" | quote }}
  max: {{ .Values.backoff.max | default "30s" | quote }}
  multiplier: {{ .Values.backoff.multiplier | default 2.0 }}
  jitter: {{ .Values.backoff.jitter | default 0.2 }}

# -----------------------------------------------------------------------------
# Pipelines Configuration
# -----------------------------------------------------------------------------
pipelines:
  metrics:
    enabled: {{ .Values.pipelines.metrics.enabled | default true }}
    also_expose_prometheus: {{ .Values.pipelines.metrics.alsoExposePrometheus | default true }}
  traces:
    enabled: {{ .Values.pipelines.traces.enabled | default true }}
  logs:
    enabled: {{ .Values.pipelines.logs.enabled | default true }}
    filelog:
      include:
        {{- range .Values.pipelines.logs.filelog.include | default (list "/var/log/containers/*.log") }}
        - {{ . }}
        {{- end }}
      exclude:
        {{- range .Values.pipelines.logs.filelog.exclude | default (list "/var/log/containers/*telegen*.log") }}
        - {{ . }}
        {{- end }}
      position_file: {{ .Values.pipelines.logs.filelog.positionFile | default "/var/lib/telegen/positions.json" }}
      poll_interval: {{ .Values.pipelines.logs.filelog.pollInterval | default "500ms" }}
  jfr:
    enabled: {{ .Values.pipelines.jfr.enabled | default false }}
    input_dir: {{ .Values.pipelines.jfr.inputDir | default "/var/log/jfr" }}
    output_dir: {{ .Values.pipelines.jfr.outputDir | default "/var/log/jfr-json" }}
    poll_interval: {{ .Values.pipelines.jfr.pollInterval | default "5s" }}
    sample_interval_ms: {{ .Values.pipelines.jfr.sampleIntervalMs | default 10 }}
    jfr_command: {{ .Values.pipelines.jfr.jfrCommand | default "jfr" }}
    workers: {{ .Values.pipelines.jfr.workers | default 2 }}
    pretty_json: {{ .Values.pipelines.jfr.prettyJson | default false }}

# -----------------------------------------------------------------------------
# Export Configuration
# -----------------------------------------------------------------------------
exports:
  remoteWrite:
    mode: {{ .Values.remoteWrite.mode | default "active" }}
    tls:
      enable: {{ .Values.remoteWrite.tls.enabled | default false }}
      ca_file: {{ .Values.remoteWrite.tls.caFile | default "" | quote }}
      cert_file: {{ .Values.remoteWrite.tls.certFile | default "" | quote }}
      key_file: {{ .Values.remoteWrite.tls.keyFile | default "" | quote }}
      insecure_skip_verify: {{ .Values.remoteWrite.tls.insecureSkipVerify | default false }}
    endpoints: {{ .Values.remoteWrite.endpoints | default list | toJson }}
  otlp:
    send_mode: failover
    tls:
      enable: {{ .Values.otlp.tls.enabled | default false }}
      ca_file: {{ .Values.otlp.tls.caFile | default "" | quote }}
      cert_file: {{ .Values.otlp.tls.certFile | default "" | quote }}
      key_file: {{ .Values.otlp.tls.keyFile | default "" | quote }}
      insecure_skip_verify: {{ .Values.otlp.tls.insecureSkipVerify | default false }}
    grpc:
      enabled: {{ eq (.Values.otlp.protocol | default "grpc") "grpc" }}
      endpoint: {{ include "telegen.otlpEndpoint" . | quote }}
      headers: {{ .Values.otlp.headers | default dict | toJson }}
      insecure: {{ .Values.otlp.insecure | default true }}
      gzip: {{ .Values.otlp.gzip | default true }}
      timeout: {{ .Values.otlp.timeout | default "10s" | quote }}
    http:
      enabled: {{ eq (.Values.otlp.protocol | default "grpc") "http" }}
      endpoint: {{ include "telegen.otlpEndpoint" . | quote }}
      traces_path: "/v1/traces"
      logs_path: "/v1/logs"
      metrics_path: "/v1/metrics"
      headers: {{ .Values.otlp.headers | default dict | toJson }}
      gzip: {{ .Values.otlp.gzip | default true }}
      timeout: {{ .Values.otlp.timeout | default "10s" | quote }}

# -----------------------------------------------------------------------------
# OpenTelemetry Metrics Export Configuration
# -----------------------------------------------------------------------------
otel_metrics_export:
  protocol: {{ .Values.otelMetricsExport.protocol | default "unset" }}
  metrics_protocol: {{ .Values.otelMetricsExport.metricsProtocol | default "unset" }}
  otel_interval_ms: {{ .Values.otelMetricsExport.otelIntervalMs | default 60000 }}
  buckets:
    duration_histogram_buckets: {{ .Values.otelMetricsExport.buckets.durationHistogramBuckets | default (list 0.005 0.01 0.025 0.05 0.1 0.25 0.5 1 2.5 5 10) | toJson }}
    request_size_histogram_buckets: {{ .Values.otelMetricsExport.buckets.requestSizeHistogramBuckets | default (list 0 100 1024 10240 102400 1048576) | toJson }}
  reporters_cache_len: {{ .Values.otelMetricsExport.reportersCacheLen | default 256 }}
  histogram_aggregation: {{ .Values.otelMetricsExport.histogramAggregation | default "explicit" }}
  instrumentations:
    {{- range .Values.otelMetricsExport.instrumentations | default (list "all") }}
    - {{ . }}
    {{- end }}
  ttl: {{ .Values.otelMetricsExport.ttl | default "5m" }}

# -----------------------------------------------------------------------------
# OpenTelemetry Traces Export Configuration
# -----------------------------------------------------------------------------
otel_traces_export:
  protocol: {{ .Values.otelTracesExport.protocol | default "unset" }}
  traces_protocol: {{ .Values.otelTracesExport.tracesProtocol | default "unset" }}
  max_queue_size: {{ .Values.otelTracesExport.maxQueueSize | default 4096 }}
  batch_timeout: {{ .Values.otelTracesExport.batchTimeout | default "15s" }}
  reporters_cache_len: {{ .Values.otelTracesExport.reportersCacheLen | default 256 }}
  instrumentations:
    {{- range .Values.otelTracesExport.instrumentations | default (list "http" "grpc" "sql" "redis" "kafka" "mqtt" "mongo") }}
    - {{ . }}
    {{- end }}

# -----------------------------------------------------------------------------
# Prometheus Export Configuration
# -----------------------------------------------------------------------------
prometheus_export:
  enabled: {{ .Values.prometheusExport.enabled | default true }}
  path: {{ .Values.prometheusExport.path | default "/metrics" }}
  port: {{ .Values.prometheusExport.port | default 0 }}
  buckets:
    duration_histogram_buckets: {{ .Values.prometheusExport.buckets.durationHistogramBuckets | default (list 0.005 0.01 0.025 0.05 0.1 0.25 0.5 1 2.5 5 10) | toJson }}
  instrumentations:
    {{- range .Values.prometheusExport.instrumentations | default (list "all") }}
    - {{ . }}
    {{- end }}
  ttl: {{ .Values.prometheusExport.ttl | default "5m" }}
  span_metrics_service_cache_size: {{ .Values.prometheusExport.spanMetricsServiceCacheSize | default 10000 }}

# -----------------------------------------------------------------------------
# Anomaly Detection Configuration
# -----------------------------------------------------------------------------
{{- if .Values.anomalyDetection.enabled }}
analytics:
  anomaly_detection:
    enabled: true
    isolation_forest:
      num_trees: {{ .Values.anomalyDetection.isolationForest.numTrees | default 100 }}
      subsample_size: {{ .Values.anomalyDetection.isolationForest.subsampleSize | default 256 }}
      threshold: {{ .Values.anomalyDetection.isolationForest.threshold | default 0.5 }}
  rca:
    enabled: {{ .Values.rca.enabled | default true }}
    max_why_depth: {{ .Values.rca.maxWhyDepth | default 5 }}
    correlation_window: {{ .Values.rca.correlationWindow | default "5m" | quote }}
{{- end }}

# -----------------------------------------------------------------------------
# Debug Configuration
# -----------------------------------------------------------------------------
trace_printer: {{ .Values.debug.tracePrinter | default "disabled" }}
profile_port: {{ .Values.debug.profilePort | default 0 }}
{{- end }}
{{- end }}

{{/*
Generate collector mode specific fully loaded configuration
*/}}
{{- define "telegen.collectorConfig" -}}
# =============================================================================
# Telegen v2.0 Collector Configuration (Generated by Helm)
# =============================================================================

# -----------------------------------------------------------------------------
# Core Collector Configuration
# -----------------------------------------------------------------------------
agent:
  service_name: {{ .Values.collector.serviceName | default "telegen-collector" | quote }}
  instance_id: "${HOSTNAME}"
  mode: collector
  log_level: {{ .Values.collector.logLevel | default "INFO" }}
  log_format: {{ .Values.collector.logFormat | default "json" }}
  shutdown_timeout: 10s
  enforce_sys_caps: false

# -----------------------------------------------------------------------------
# Self-Telemetry Configuration
# -----------------------------------------------------------------------------
selfTelemetry:
  listen: ":{{ .Values.service.port | default 19090 }}"
  health_listen: ":{{ .Values.service.healthPort | default 8080 }}"
  prometheus_namespace: "telegen"
  pprof_enabled: false
  pprof_port: 6060

# -----------------------------------------------------------------------------
# Internal Metrics Configuration
# -----------------------------------------------------------------------------
internal_metrics:
  exporter: disabled
  prometheus:
    port: 0
    path: "/internal/metrics"
  bpf_metric_scrape_interval: 15s

# -----------------------------------------------------------------------------
# Queues Configuration
# -----------------------------------------------------------------------------
queues:
  traces:
    mem_limit: "256Mi"
    max_age: "6h"
  logs:
    mem_limit: "256Mi"
    max_age: "24h"
  metrics:
    mem_limit: "128Mi"
    max_age: "5m"

# -----------------------------------------------------------------------------
# Backoff Configuration
# -----------------------------------------------------------------------------
backoff:
  initial: "500ms"
  max: "30s"
  multiplier: 2.0
  jitter: 0.2

# -----------------------------------------------------------------------------
# SNMP Receiver Configuration
# -----------------------------------------------------------------------------
snmp_receiver:
  enabled: {{ .Values.collector.snmp.enabled | default false }}
  trap_receiver:
    enabled: {{ .Values.collector.snmp.trapReceiver.enabled | default true }}
    listen_address: {{ .Values.collector.snmp.trapReceiver.listenAddress | default "0.0.0.0:1162" | quote }}
    community_strings:
      {{- range .Values.collector.snmp.trapReceiver.communityStrings | default (list "public" "private") }}
      - {{ . }}
      {{- end }}
    {{- if .Values.collector.snmp.trapReceiver.v3Users }}
    v3_users:
      {{- toYaml .Values.collector.snmp.trapReceiver.v3Users | nindent 6 }}
    {{- else }}
    v3_users: []
    {{- end }}
  polling:
    enabled: {{ .Values.collector.snmp.polling.enabled | default true }}
    default_interval: {{ .Values.collector.snmp.polling.defaultInterval | default "60s" }}
    timeout: {{ .Values.collector.snmp.polling.timeout | default "10s" }}
    retries: {{ .Values.collector.snmp.polling.retries | default 3 }}
    max_concurrent: {{ .Values.collector.snmp.polling.maxConcurrent | default 100 }}
  {{- if .Values.collector.snmp.targets }}
  targets:
    {{- toYaml .Values.collector.snmp.targets | nindent 4 }}
  {{- else }}
  targets: []
  {{- end }}
  discovery:
    enabled: {{ .Values.collector.snmp.discovery.enabled | default false }}
    networks: {{ .Values.collector.snmp.discovery.networks | default list | toJson }}
    interval: {{ .Values.collector.snmp.discovery.interval | default "1h" }}
    community_strings:
      {{- range .Values.collector.snmp.discovery.communityStrings | default (list "public") }}
      - {{ . }}
      {{- end }}
  mibs:
    search_paths:
      {{- range .Values.collector.snmp.mibs.searchPaths | default (list "/usr/share/snmp/mibs" "/opt/telegen/mibs") }}
      - {{ . }}
      {{- end }}
    load_standard: {{ .Values.collector.snmp.mibs.loadStandard | default true }}
    custom_mibs: {{ .Values.collector.snmp.mibs.customMibs | default list | toJson }}
  output:
    prometheus:
      enabled: {{ .Values.collector.snmp.output.prometheus.enabled | default true }}
      listen_address: {{ .Values.collector.snmp.output.prometheus.listenAddress | default ":9116" | quote }}
      path: {{ .Values.collector.snmp.output.prometheus.path | default "/metrics" }}
    remote_write:
      enabled: {{ .Values.collector.snmp.output.remoteWrite.enabled | default false }}
      endpoints: {{ .Values.collector.snmp.output.remoteWrite.endpoints | default list | toJson }}

# -----------------------------------------------------------------------------
# Storage Metrics Configuration
# -----------------------------------------------------------------------------
storage:
  enabled: {{ .Values.collector.storage.enabled | default false }}
  collect_interval: {{ .Values.collector.storage.collectInterval | default "60s" }}
  {{- if .Values.collector.storage.dellPowerStore }}
  dell_powerstore:
    {{- toYaml .Values.collector.storage.dellPowerStore | nindent 4 }}
  {{- end }}
  {{- if .Values.collector.storage.hpePrimera }}
  hpe_primera:
    {{- toYaml .Values.collector.storage.hpePrimera | nindent 4 }}
  {{- end }}
  {{- if .Values.collector.storage.pureFlashArray }}
  pure_flasharray:
    {{- toYaml .Values.collector.storage.pureFlashArray | nindent 4 }}
  {{- end }}
  {{- if .Values.collector.storage.netappOntap }}
  netapp_ontap:
    {{- toYaml .Values.collector.storage.netappOntap | nindent 4 }}
  {{- end }}
  otlp:
    enabled: {{ .Values.collector.storage.otlp.enabled | default true }}
    endpoint: {{ .Values.collector.storage.otlp.endpoint | default (include "telegen.otlpEndpoint" .) | quote }}

# -----------------------------------------------------------------------------
# Cloud Provider Configuration
# -----------------------------------------------------------------------------
cloud:
  auto_detect: true
  detection_timeout: 10s
  detection_interval: 5m
  collect_metrics: false
  metrics_interval: 30s
  discover_resources: false
  resource_interval: 5m
  aws:
    enabled: true
    timeout: 200ms
    refresh_interval: 15m
    collect_tags: false
    tag_allowlist: []
    region: ""
    imdsv2_only: true
    imds_endpoint: ""
    imds_timeout: 2s
  gcp:
    enabled: false
  azure:
    enabled: false

# -----------------------------------------------------------------------------
# Export Configuration
# -----------------------------------------------------------------------------
exports:
  remoteWrite:
    mode: active
    tls:
      enable: false
      ca_file: ""
      cert_file: ""
      key_file: ""
      insecure_skip_verify: false
    endpoints: []
  otlp:
    send_mode: failover
    tls:
      enable: {{ .Values.otlp.tls.enabled | default false }}
      ca_file: {{ .Values.otlp.tls.caFile | default "" | quote }}
      cert_file: {{ .Values.otlp.tls.certFile | default "" | quote }}
      key_file: {{ .Values.otlp.tls.keyFile | default "" | quote }}
      insecure_skip_verify: {{ .Values.otlp.tls.insecureSkipVerify | default false }}
    grpc:
      enabled: {{ eq (.Values.otlp.protocol | default "grpc") "grpc" }}
      endpoint: {{ include "telegen.otlpEndpoint" . | quote }}
      headers: {{ .Values.otlp.headers | default dict | toJson }}
      insecure: {{ .Values.otlp.insecure | default true }}
      gzip: {{ .Values.otlp.gzip | default true }}
      timeout: {{ .Values.otlp.timeout | default "10s" | quote }}
    http:
      enabled: {{ eq (.Values.otlp.protocol | default "grpc") "http" }}
      endpoint: {{ include "telegen.otlpEndpoint" . | quote }}
      traces_path: "/v1/traces"
      logs_path: "/v1/logs"
      metrics_path: "/v1/metrics"
      headers: {{ .Values.otlp.headers | default dict | toJson }}
      gzip: {{ .Values.otlp.gzip | default true }}
      timeout: {{ .Values.otlp.timeout | default "10s" | quote }}

# -----------------------------------------------------------------------------
# Prometheus Export Configuration
# -----------------------------------------------------------------------------
prometheus_export:
  enabled: true
  path: /metrics
  port: 0
  buckets:
    duration_histogram_buckets:
      - 0.005
      - 0.01
      - 0.025
      - 0.05
      - 0.1
      - 0.25
      - 0.5
      - 1
      - 2.5
      - 5
      - 10
  instrumentations:
    - all
  ttl: 5m
  span_metrics_service_cache_size: 10000

# -----------------------------------------------------------------------------
# Debug Configuration
# -----------------------------------------------------------------------------
trace_printer: disabled
profile_port: 0
{{- end }}
