#!/bin/bash
# Telegen v2.1 Linux Installation Script
# Task: DEP-013
# Usage: curl -sSL https://get.telegen.io | bash
#   or:  ./install-linux.sh [agent|collector]

set -e

# Configuration
TELEGEN_VERSION="${TELEGEN_VERSION:-v2.1.0}"
TELEGEN_MODE="${1:-agent}"
TELEGEN_ENDPOINT="${TELEGEN_ENDPOINT:-otel-collector:4317}"
TELEGEN_INSTALL_DIR="${TELEGEN_INSTALL_DIR:-/usr/local/bin}"
TELEGEN_CONFIG_DIR="${TELEGEN_CONFIG_DIR:-/etc/telegen}"
TELEGEN_DATA_DIR="${TELEGEN_DATA_DIR:-/var/lib/telegen}"
TELEGEN_LOG_DIR="${TELEGEN_LOG_DIR:-/var/log/telegen}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if running as root
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root (use sudo)"
        exit 1
    fi
}

# Detect architecture
detect_arch() {
    local arch=$(uname -m)
    case "$arch" in
        x86_64|amd64)
            echo "amd64"
            ;;
        aarch64|arm64)
            echo "arm64"
            ;;
        *)
            log_error "Unsupported architecture: $arch"
            exit 1
            ;;
    esac
}

# Detect OS
detect_os() {
    if [[ -f /etc/os-release ]]; then
        . /etc/os-release
        echo "$ID"
    else
        log_error "Cannot detect OS"
        exit 1
    fi
}

# Check kernel version for eBPF support
check_kernel() {
    local kernel_version=$(uname -r | cut -d. -f1-2)
    local major=$(echo "$kernel_version" | cut -d. -f1)
    local minor=$(echo "$kernel_version" | cut -d. -f2)
    
    if [[ "$major" -lt 5 ]] || [[ "$major" -eq 5 && "$minor" -lt 4 ]]; then
        log_warn "Kernel version $kernel_version detected. Recommended: >= 5.4 for full eBPF support"
    else
        log_info "Kernel version $kernel_version OK"
    fi
}

# Check for required kernel features
check_bpf_support() {
    if [[ ! -d /sys/fs/bpf ]]; then
        log_warn "BPF filesystem not mounted. Attempting to mount..."
        mount -t bpf bpf /sys/fs/bpf || log_warn "Failed to mount BPF filesystem"
    fi
    
    if [[ ! -d /sys/kernel/debug ]]; then
        log_warn "debugfs not mounted. Attempting to mount..."
        mount -t debugfs debugfs /sys/kernel/debug || log_warn "Failed to mount debugfs"
    fi
}

# Download and install binary
install_binary() {
    local arch=$(detect_arch)
    local download_url="https://github.com/platformbuilds/telegen/releases/download/${TELEGEN_VERSION}/telegen-linux-${arch}"
    
    log_info "Downloading Telegen ${TELEGEN_VERSION} for linux/${arch}..."
    
    if command -v curl &> /dev/null; then
        curl -sSL -o "${TELEGEN_INSTALL_DIR}/telegen" "$download_url"
    elif command -v wget &> /dev/null; then
        wget -q -O "${TELEGEN_INSTALL_DIR}/telegen" "$download_url"
    else
        log_error "Neither curl nor wget found. Please install one of them."
        exit 1
    fi
    
    chmod +x "${TELEGEN_INSTALL_DIR}/telegen"
    log_info "Binary installed to ${TELEGEN_INSTALL_DIR}/telegen"
}

# Create telegen user for collector mode
create_user() {
    if [[ "$TELEGEN_MODE" == "collector" ]]; then
        if ! id -u telegen &>/dev/null; then
            log_info "Creating telegen user..."
            useradd --system --no-create-home --shell /bin/false telegen || true
        fi
    fi
}

# Create directories
create_directories() {
    log_info "Creating directories..."
    mkdir -p "$TELEGEN_CONFIG_DIR"
    mkdir -p "$TELEGEN_DATA_DIR"
    mkdir -p "$TELEGEN_LOG_DIR"
    
    if [[ "$TELEGEN_MODE" == "collector" ]]; then
        chown telegen:telegen "$TELEGEN_DATA_DIR" "$TELEGEN_LOG_DIR"
    fi
}

# Create configuration file
create_config() {
    local config_file="${TELEGEN_CONFIG_DIR}/config.yaml"
    
    if [[ -f "$config_file" ]]; then
        log_warn "Configuration file already exists. Backing up to ${config_file}.bak"
        cp "$config_file" "${config_file}.bak"
    fi
    
    log_info "Creating configuration file..."
    
    if [[ "$TELEGEN_MODE" == "agent" ]]; then
        cat > "$config_file" <<EOF
# Telegen v2.0 Agent Configuration
# Generated by install-linux.sh on $(date)

telegen:
  mode: agent
  service_name: "telegen"
  instance_id: "\${HOSTNAME}"

selfTelemetry:
  listen: ":19090"
  health_listen: ":8080"

ebpf:
  enabled: true
  network:
    enabled: true
    track_tcp: true
    track_dns: true
  syscalls:
    enabled: true

discovery:
  enabled: true
  interval: "30s"

profiling:
  enabled: true
  cpu:
    enabled: true
    sample_rate: 99
  memory:
    enabled: true
  offcpu:
    enabled: true

security:
  enabled: true
  syscall_audit:
    enabled: true
  file_integrity:
    enabled: true
  container_escape:
    enabled: true

pipelines:
  traces:
    enabled: true
  logs:
    enabled: true
    filelog:
      include:
        - "/var/log/*.log"
        - "/var/log/**/*.log"
      exclude:
        - "/var/log/telegen/*.log"
      position_file: "${TELEGEN_DATA_DIR}/positions.json"
  metrics:
    enabled: true
  profiles:
    enabled: true

exports:
  otlp:
    grpc:
      enabled: true
      endpoint: "${TELEGEN_ENDPOINT}"
      insecure: true
      gzip: true
EOF
    else
        cat > "${TELEGEN_CONFIG_DIR}/collector.yaml" <<EOF
# Telegen v2.0 Collector Configuration
# Generated by install-linux.sh on $(date)

telegen:
  mode: collector
  service_name: "telegen-collector"

selfTelemetry:
  listen: ":19090"
  health_listen: ":8080"

collector:
  snmp:
    enabled: true
    poll_interval: "60s"
    targets: []
    traps:
      enabled: true
      listen_address: ":162"
  
  storage:
    enabled: false

exports:
  otlp:
    grpc:
      enabled: true
      endpoint: "${TELEGEN_ENDPOINT}"
      insecure: true
EOF
    fi
    
    log_info "Configuration created at $config_file"
}

# Create environment file
create_env_file() {
    local env_file="${TELEGEN_CONFIG_DIR}/telegen.env"
    
    log_info "Creating environment file..."
    cat > "$env_file" <<EOF
# Telegen Environment Variables
TELEGEN_OTLP_ENDPOINT=${TELEGEN_ENDPOINT}
TELEGEN_MODE=${TELEGEN_MODE}
TELEGEN_LOG_LEVEL=info
GOMAXPROCS=4
EOF
}

# Install systemd service
install_systemd_service() {
    local service_file="/etc/systemd/system/telegen.service"
    
    log_info "Installing systemd service..."
    
    if [[ "$TELEGEN_MODE" == "agent" ]]; then
        cat > "$service_file" <<EOF
[Unit]
Description=Telegen Observability Agent
Documentation=https://github.com/platformbuilds/telegen
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
Group=root
EnvironmentFile=-${TELEGEN_CONFIG_DIR}/telegen.env
ExecStart=${TELEGEN_INSTALL_DIR}/telegen --mode=agent --config=${TELEGEN_CONFIG_DIR}/config.yaml
Restart=always
RestartSec=5
LimitNOFILE=65536
LimitMEMLOCK=infinity
StandardOutput=journal
StandardError=journal
SyslogIdentifier=telegen

[Install]
WantedBy=multi-user.target
EOF
    else
        cat > "$service_file" <<EOF
[Unit]
Description=Telegen Observability Collector
Documentation=https://github.com/platformbuilds/telegen
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=telegen
Group=telegen
EnvironmentFile=-${TELEGEN_CONFIG_DIR}/telegen.env
ExecStart=${TELEGEN_INSTALL_DIR}/telegen --mode=collector --config=${TELEGEN_CONFIG_DIR}/collector.yaml
Restart=always
RestartSec=5
LimitNOFILE=65536
AmbientCapabilities=CAP_NET_BIND_SERVICE
NoNewPrivileges=yes
ProtectSystem=strict
ReadWritePaths=${TELEGEN_DATA_DIR} ${TELEGEN_LOG_DIR}
StandardOutput=journal
StandardError=journal
SyslogIdentifier=telegen-collector

[Install]
WantedBy=multi-user.target
EOF
    fi
    
    systemctl daemon-reload
    log_info "systemd service installed"
}

# Enable and start service
start_service() {
    log_info "Enabling and starting Telegen service..."
    systemctl enable telegen
    systemctl start telegen
    
    # Wait a moment and check status
    sleep 2
    if systemctl is-active --quiet telegen; then
        log_info "Telegen is running!"
    else
        log_error "Telegen failed to start. Check: journalctl -u telegen -f"
        exit 1
    fi
}

# Print summary
print_summary() {
    echo ""
    echo "=============================================="
    echo "  Telegen ${TELEGEN_VERSION} Installation Complete!"
    echo "=============================================="
    echo ""
    echo "  Mode:      ${TELEGEN_MODE}"
    echo "  Binary:    ${TELEGEN_INSTALL_DIR}/telegen"
    echo "  Config:    ${TELEGEN_CONFIG_DIR}/config.yaml"
    echo "  Data:      ${TELEGEN_DATA_DIR}"
    echo "  Endpoint:  ${TELEGEN_ENDPOINT}"
    echo ""
    echo "  Commands:"
    echo "    Status:   systemctl status telegen"
    echo "    Logs:     journalctl -u telegen -f"
    echo "    Restart:  systemctl restart telegen"
    echo "    Stop:     systemctl stop telegen"
    echo ""
    echo "  Metrics:    http://localhost:19090/metrics"
    echo "  Health:     http://localhost:8080/healthz"
    echo ""
}

# Uninstall function
uninstall() {
    log_info "Uninstalling Telegen..."
    
    systemctl stop telegen 2>/dev/null || true
    systemctl disable telegen 2>/dev/null || true
    
    rm -f /etc/systemd/system/telegen.service
    rm -f "${TELEGEN_INSTALL_DIR}/telegen"
    
    systemctl daemon-reload
    
    log_info "Telegen uninstalled. Config and data directories preserved."
    log_info "To remove completely: rm -rf ${TELEGEN_CONFIG_DIR} ${TELEGEN_DATA_DIR} ${TELEGEN_LOG_DIR}"
}

# Main
main() {
    echo ""
    echo "=============================================="
    echo "  Telegen ${TELEGEN_VERSION} Installer"
    echo "=============================================="
    echo ""
    
    if [[ "$1" == "uninstall" ]]; then
        check_root
        uninstall
        exit 0
    fi
    
    check_root
    
    log_info "Installing Telegen in ${TELEGEN_MODE} mode..."
    
    check_kernel
    check_bpf_support
    install_binary
    create_user
    create_directories
    create_config
    create_env_file
    install_systemd_service
    start_service
    print_summary
}

main "$@"
